"""CLI parser tree. Handlers and shared argument helpers are explicitly injected."""
from __future__ import annotations
import argparse

def add_campaign_flags(parser: argparse.ArgumentParser, *, deps) -> None:
    parser.add_argument('--name')
    parser.add_argument('--objective-type')
    parser.add_argument('--budget', type=float)
    parser.add_argument('--budget-mode')
    parser.add_argument('--operation-status')
    parser.add_argument('--campaign-type')
    parser.add_argument('--sales-destination')
    parser.add_argument('--optimization-goal')
    parser.add_argument('--special-industries', nargs='*')

def add_tiktok_campaign_group(parent_subparsers, *, name: str, smart_plus: bool, help_text: str, deps) -> None:
    campaigns = parent_subparsers.add_parser(name, help=help_text)
    campaigns_sub = campaigns.add_subparsers(dest=f"{name.replace('-', '_')}_command", required=True)
    p = campaigns_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--campaign-id', dest='campaign_ids', action='append')
    p.add_argument('--name')
    p.add_argument('--objective-type')
    p.add_argument('--primary-status')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.add_argument('--fields', nargs='*')
    p.add_argument('--exclude-field-types', nargs='*')
    p.set_defaults(func=deps.command_tiktok_campaigns_list, smart_plus=smart_plus)
    p = campaigns_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('campaign_id')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_campaigns_get, smart_plus=smart_plus)
    p = campaigns_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    add_campaign_flags(p, deps=deps)
    if smart_plus:
        p.add_argument('--page-id', help='App Profile Page ID to use when campaign_app_profile_page_state is ON')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_campaigns_create, smart_plus=smart_plus)
    p = campaigns_sub.add_parser('update')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('campaign_id')
    p.add_argument('--name')
    p.add_argument('--budget', type=float)
    p.add_argument('--po-number')
    p.add_argument('--special-industries', nargs='*')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_campaigns_update, smart_plus=smart_plus)
    p = campaigns_sub.add_parser('status')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('campaign_ids', nargs='+')
    p.add_argument('--operation-status', required=True)
    p.add_argument('--postback-window-mode')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_campaigns_status, smart_plus=smart_plus)
    p = campaigns_sub.add_parser('copy')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('campaign_id', help='Source campaign ID to copy')
    p.add_argument('--name', required=True, help='Name for the new campaign(s)')
    p.add_argument('--copies', type=int, default=1, help='Number of copies to create (default: 1)')
    p.add_argument('--operation-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new campaigns (default: DISABLE)')
    p.add_argument('--adgroup-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new adgroups (default: DISABLE)')
    p.add_argument('--ad-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new ads (default: DISABLE; explicit ENABLE activates)')
    p.add_argument('--page-id', help='App Profile Page ID to use when campaign_app_profile_page_state is ON')
    p.add_argument('--landing-page-url', help='Override landing page URL for website ads during copy')
    p.add_argument('--copy-route', choices=['auto', 'normal', 'smartplus'], default='auto', help='Target API route for the copy flow (default: auto)')
    p.add_argument('--skip-adgroups', action='store_true', help='Skip copying adgroups')
    p.add_argument('--skip-ads', action='store_true', help='Skip copying ads')
    p.add_argument('--verbose', '-v', action='store_true', help='Show detailed progress')
    p.set_defaults(func=deps.command_tiktok_campaigns_copy, smart_plus=smart_plus)
    if smart_plus:
        p = campaigns_sub.add_parser('bootstrap-app')
        deps.add_tiktok_auth_arguments(p)
        p.add_argument('--name', required=True, help='Name for the new SmartPlus app campaign')
        p.add_argument('--app-id', help='Target TikTok app ID to match')
        p.add_argument('--app-name', help='Target TikTok app name to match when app_id is unknown')
        p.add_argument('--app-promotion-type', default='APP_INSTALL', help='App promotion type filter (default: APP_INSTALL)')
        p.add_argument('--template-campaign-id', help='Explicit SmartPlus APP_PROMOTION campaign to use as the template')
        p.add_argument('--copies', type=int, default=1, help='Number of campaign copies to create (default: 1)')
        p.add_argument('--operation-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new campaigns (default: DISABLE)')
        p.add_argument('--adgroup-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new adgroups (default: DISABLE)')
        p.add_argument('--ad-status', choices=['ENABLE', 'DISABLE'], default='DISABLE', help='Operation status for new ads (default: DISABLE; explicit ENABLE activates)')
        p.add_argument('--page-id', help='App Profile Page ID to use when campaign_app_profile_page_state is ON')
        p.add_argument('--dry-run', action='store_true', help='Only resolve the best-matched template and assets')
        p.add_argument('--verbose', '-v', action='store_true', help='Show detailed progress')
        p.set_defaults(func=deps.command_tiktok_smartplus_campaigns_bootstrap_app, smart_plus=True)

def add_tiktok_gmv_max_campaign_group(parent_subparsers, *, deps) -> None:
    campaigns = parent_subparsers.add_parser('gmv-max-campaigns', aliases=['gmvmax-campaigns'], help='TikTok GMV Max campaigns')
    campaigns_sub = campaigns.add_subparsers(dest='gmv_max_campaigns_command', required=True)
    p = campaigns_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--gmv-max-promotion-type', dest='gmv_max_promotion_types', action='append', choices=['PRODUCT_GMV_MAX', 'LIVE_GMV_MAX'], help='GMV Max campaign type. Defaults to PRODUCT_GMV_MAX.')
    p.add_argument('--store-id', dest='store_ids', action='append')
    p.add_argument('--campaign-id', dest='campaign_ids', action='append')
    p.add_argument('--name')
    p.add_argument('--primary-status')
    p.add_argument('--creation-filter-start-time')
    p.add_argument('--creation-filter-end-time')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_gmv_max_campaigns_list)
    p = campaigns_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('campaign_id')
    p.set_defaults(func=deps.command_tiktok_gmv_max_campaigns_get)
    p = campaigns_sub.add_parser('item-previews')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--campaign-id', dest='campaign_ids', action='append', required=True, help='GMV Max campaign ID to read via /campaign/gmv_max/info/. Repeatable.')
    p.add_argument('--item-id', dest='item_ids', action='append', help='Optional target item_id to diagnose inside the returned campaign item_list. Repeatable.')
    p.add_argument('--no-identity-video-info', action='store_true', help='Skip /identity/video/info enrichment for item_list rows.')
    p.add_argument('--identity-video-info', action='store_true', help='Force /identity/video/info enrichment even when no --item-id target is provided.')
    p.add_argument('--out', help='Optional JSON output path for the item_id -> preview map.')
    p.set_defaults(func=deps.command_tiktok_gmv_max_campaigns_item_previews)

def add_tiktok_gmv_max_custom_anchor_video_group(parent_subparsers, *, deps) -> None:
    videos = parent_subparsers.add_parser('gmv-max-custom-anchor-videos', aliases=['gmvmax-custom-anchor-videos', 'gmv-max-custom-videos', 'gmvmax-custom-videos'], help='TikTok GMV Max customized TikTok post previews')
    videos_sub = videos.add_subparsers(dest='gmv_max_custom_anchor_videos_command', required=True)
    p = videos_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.add_argument('--store-id', help='Required unless provided in --payload-json/--payload-file.')
    p.add_argument('--store-authorized-bc-id', help='Required unless provided in --payload-json/--payload-file.')
    p.add_argument('--creative-source', default='CUSTOMIZED')
    p.add_argument('--spu-id', dest='spu_ids', action='append')
    p.add_argument('--keyword', help='Keyword search. Numeric item_id can be used for exact preview enrichment probes.')
    p.add_argument('--campaign-id')
    p.add_argument('--need-auth-code-video', action='store_true', default=None)
    p.add_argument('--identity-list-json', help='JSON array for identity_list.')
    p.add_argument('--sort-field')
    p.add_argument('--sort-type')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_gmv_max_custom_anchor_videos_list)

def add_tiktok_gmv_max_video_group(parent_subparsers, *, deps) -> None:
    videos = parent_subparsers.add_parser('gmv-max-videos', aliases=['gmvmax-videos'], help='TikTok posts available for Product GMV Max campaigns')
    videos_sub = videos.add_subparsers(dest='gmv_max_videos_command', required=True)
    p = videos_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.add_argument('--store-id', help='Required unless provided in --payload-json/--payload-file.')
    p.add_argument('--store-authorized-bc-id', help='Required unless provided in --payload-json/--payload-file.')
    p.add_argument('--spu-id', dest='spu_ids', action='append', help='Product SPU/item_group_id filter. Repeatable.')
    p.add_argument('--custom-posts-eligible', action='store_true', default=None)
    p.add_argument('--sort-field', choices=['GMV', 'POST_TIME', 'VIDEO_VIEWS', 'VIDEO_LIKES', 'CLICK_THROUGH_RATE', 'PRODUCT_CLICKS'])
    p.add_argument('--sort-type', choices=['ASC', 'DESC'])
    p.add_argument('--keyword', help='Post caption or exact numeric item_id/post ID.')
    p.add_argument('--need-auth-code-video', action='store_true', default=None, help='Include AUTH_CODE identity posts when set.')
    p.add_argument('--no-need-auth-code-video', action='store_true', default=False, help='Pass need_auth_code_video=false explicitly.')
    p.add_argument('--identity-list-json', help='JSON array for identity_list.')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=10)
    p.set_defaults(func=deps.command_tiktok_gmv_max_videos_list)

def add_tiktok_gmv_max_product_group(parent_subparsers, *, deps) -> None:
    products = parent_subparsers.add_parser('gmv-max-products', aliases=['gmvmax-products', 'store-products'], help='TikTok Shop products available for Product GMV Max campaigns')
    products_sub = products.add_subparsers(dest='gmv_max_products_command', required=True)
    p = products_sub.add_parser('list', help='Get TikTok Shop products through /store/product/get/.')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.add_argument('--bc-id', required=True, help='Business Center ID.')
    p.add_argument('--store-id', required=True, help='TikTok Shop store ID.')
    p.add_argument('--item-group-id', dest='item_group_ids', action='append', help='SPU/item_group_id filter. Max 10.')
    p.add_argument('--product-name', help='Product name keyword filter.')
    p.add_argument('--ad-creation-eligible', choices=['GMV_MAX', 'CUSTOM_SHOP_ADS'], default='GMV_MAX')
    p.add_argument('--sort-field', choices=['min_price', 'historical_sales'])
    p.add_argument('--sort-type', choices=['ASC', 'DESC'])
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--normalized', action='store_true', help='Print the normalized report-friendly payload.')
    p.add_argument('--out', help='Optional JSON output path for the normalized product map.')
    p.set_defaults(func=deps.command_tiktok_gmv_max_products_list)

def add_tiktok_gmv_max_report_group(parent_subparsers, *, deps) -> None:
    reports = parent_subparsers.add_parser('gmv-max-reports', aliases=['gmvmax-reports'], help='TikTok GMV Max reports')
    reports_sub = reports.add_subparsers(dest='gmv_max_reports_command', required=True)
    p = reports_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--store-id', dest='store_ids', action='append', required=True)
    p.add_argument('--dimension', dest='dimensions', action='append', choices=deps.TIKTOK_GMV_MAX_REPORT_DIMENSION_CHOICES)
    p.add_argument('--level', choices=sorted(deps.TIKTOK_GMV_MAX_REPORT_LEVEL_DIMENSIONS), help='Shortcut for common dimension groupings. Ignored when --dimension is provided.')
    p.add_argument('--time-grain', choices=sorted(deps.TIKTOK_GMV_MAX_REPORT_TIME_GRAIN_DIMENSIONS), default='none', help='Append stat_time_day or stat_time_hour to the selected --level dimensions.')
    p.add_argument('--metric', dest='metrics', action='append', help='Defaults to GMV Max KPI metrics; item_id creative dimensions also include product click/video-view metrics.')
    p.add_argument('--start-date', required=True)
    p.add_argument('--end-date', required=True)
    p.add_argument('--gmv-max-promotion-type', dest='gmv_max_promotion_types', action='append')
    p.add_argument('--campaign-id', dest='campaign_ids', action='append')
    p.add_argument('--campaign-name')
    p.add_argument('--campaign-status', dest='campaign_statuses', action='append')
    p.add_argument('--creative-delivery-status', dest='creative_delivery_statuses', action='append')
    p.add_argument('--creative-type', dest='creative_types', action='append')
    p.add_argument('--item-group-id', dest='item_group_ids', action='append')
    p.add_argument('--item-id', dest='item_ids', action='append')
    p.add_argument('--room-id', dest='room_ids', action='append')
    p.add_argument('--search-word')
    deps.add_filtering_arguments(p)
    p.add_argument('--sort-field')
    p.add_argument('--sort-type')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--enable-total-metrics', action='store_true', default=None)
    p.set_defaults(func=deps.command_tiktok_gmv_max_reports_get)

def add_tiktok_adgroup_group(parent_subparsers, *, name: str, smart_plus: bool, help_text: str, deps) -> None:
    adgroups = parent_subparsers.add_parser(name, help=help_text)
    adgroups_sub = adgroups.add_subparsers(dest=f"{name.replace('-', '_')}_command", required=True)
    p = adgroups_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--adgroup-id', dest='adgroup_ids', action='append')
    p.add_argument('--campaign-id', dest='campaign_ids', action='append')
    p.add_argument('--name')
    p.add_argument('--objective-type')
    p.add_argument('--optimization-goal')
    p.add_argument('--primary-status')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.add_argument('--fields', nargs='*')
    p.add_argument('--exclude-field-types', nargs='*')
    p.set_defaults(func=deps.command_tiktok_adgroups_list, smart_plus=smart_plus)
    p = adgroups_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('adgroup_id')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_adgroups_get, smart_plus=smart_plus)
    p = adgroups_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--campaign-id')
    p.add_argument('--name')
    p.add_argument('--billing-event')
    p.add_argument('--optimization-goal')
    p.add_argument('--operation-status')
    p.add_argument('--budget', type=float)
    p.add_argument('--budget-mode')
    p.add_argument('--bid-price', type=float)
    p.add_argument('--bid-type')
    p.add_argument('--promotion-type')
    p.add_argument('--promotion-website-type')
    p.add_argument('--pixel-id')
    p.add_argument('--placement-type')
    p.add_argument('--placements', nargs='*')
    p.add_argument('--start-time')
    p.add_argument('--end-time')
    p.add_argument('--schedule-type')
    p.add_argument('--targeting-spec-json')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_adgroups_create, smart_plus=smart_plus)
    p = adgroups_sub.add_parser('update')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('adgroup_id')
    p.add_argument('--name')
    p.add_argument('--budget', type=float)
    p.add_argument('--bid-price', type=float)
    p.add_argument('--roas-bid', type=float)
    p.add_argument('--conversion-bid-price', type=float)
    p.add_argument('--comment-disabled', action='store_true', default=None)
    p.add_argument('--share-disabled', action='store_true', default=None)
    p.add_argument('--pacing')
    p.add_argument('--start-time')
    p.add_argument('--end-time')
    p.add_argument('--schedule-type')
    p.add_argument('--targeting-optimization-mode')
    p.add_argument('--targeting-spec-json')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_adgroups_update, smart_plus=smart_plus)
    p = adgroups_sub.add_parser('status')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('adgroup_ids', nargs='+')
    p.add_argument('--operation-status', required=True)
    if not smart_plus:
        p.add_argument('--allow-partial-success', action='store_true', default=None)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_adgroups_status, smart_plus=smart_plus)

def add_tiktok_ad_group(parent_subparsers, *, name: str, smart_plus: bool, help_text: str, deps) -> None:
    ads = parent_subparsers.add_parser(name, help=help_text)
    ads_sub = ads.add_subparsers(dest=f"{name.replace('-', '_')}_command", required=True)
    p = ads_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--ad-id', dest='ad_ids', action='append')
    p.add_argument('--campaign-id', dest='campaign_ids', action='append')
    p.add_argument('--adgroup-id', dest='adgroup_ids', action='append')
    p.add_argument('--name')
    p.add_argument('--objective-type')
    p.add_argument('--optimization-goal')
    p.add_argument('--primary-status')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.add_argument('--fields', nargs='*')
    p.add_argument('--exclude-field-types', nargs='*')
    p.set_defaults(func=deps.command_tiktok_ads_list, smart_plus=smart_plus)
    p = ads_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('ad_id')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_ads_get, smart_plus=smart_plus)
    p = ads_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--adgroup-id', required=True)
    p.add_argument('--name')
    p.add_argument('--operation-status')
    p.add_argument('--creatives-json')
    p.add_argument('--ad-configuration-json')
    p.add_argument('--ad-text-list-json')
    p.add_argument('--auto-message-list-json')
    p.add_argument('--call-to-action-list-json')
    p.add_argument('--creative-list-json')
    p.add_argument('--deeplink-list-json')
    p.add_argument('--interactive-add-on-list-json')
    p.add_argument('--landing-page-url-list-json')
    p.add_argument('--page-list-json')
    if smart_plus:
        p.add_argument('--page-id', help='Convenience alias for SmartPlus page_list[0].page_id (App Profile Page ID)')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_ads_create, smart_plus=smart_plus)
    p = ads_sub.add_parser('update')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('ad_id')
    if not smart_plus:
        p.add_argument('--adgroup-id')
        p.add_argument('--patch-update', action='store_true', default=None)
        p.add_argument('--creatives-json')
    p.add_argument('--name')
    p.add_argument('--ad-configuration-json')
    p.add_argument('--ad-text-list-json')
    p.add_argument('--call-to-action-list-json')
    p.add_argument('--creative-list-json')
    p.add_argument('--deeplink-list-json')
    p.add_argument('--interactive-add-on-list-json')
    p.add_argument('--landing-page-url-list-json')
    p.add_argument('--page-list-json')
    if smart_plus:
        p.add_argument('--page-id', help='Convenience alias for SmartPlus page_list[0].page_id (App Profile Page ID)')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_ads_update, smart_plus=smart_plus)
    p = ads_sub.add_parser('status')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('ad_ids', nargs='+')
    p.add_argument('--operation-status', required=True)
    if not smart_plus:
        p.add_argument('--aco-ad-id', dest='aco_ad_ids', action='append')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_ads_status, smart_plus=smart_plus)

def add_tiktok_media_group(parent_subparsers, *, deps) -> None:
    media = parent_subparsers.add_parser('media', help='TikTok media upload operations')
    media_sub = media.add_subparsers(dest='media_command', required=True)
    p = media_sub.add_parser('upload-image')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--file', required=True)
    p.add_argument('--name')
    p.add_argument('--upload-type')
    p.add_argument('--file-id')
    p.add_argument('--image-signature')
    p.add_argument('--image-url')
    p.set_defaults(func=deps.command_tiktok_media_upload_image)
    p = media_sub.add_parser('upload-video')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--file', required=True)
    p.add_argument('--name')
    p.add_argument('--upload-type')
    p.add_argument('--file-id')
    p.add_argument('--video-id')
    p.add_argument('--video-signature')
    p.add_argument('--video-url')
    p.add_argument('--auto-bind-enabled', action='store_true', default=None)
    p.add_argument('--auto-fix-enabled', action='store_true', default=None)
    p.add_argument('--flaw-detect', action='store_true', default=None)
    p.add_argument('--is-third-party', action='store_true', default=None)
    p.set_defaults(func=deps.command_tiktok_media_upload_video)

def add_tiktok_images_group(parent_subparsers, *, deps) -> None:
    images = parent_subparsers.add_parser('images', help='TikTok image asset operations')
    images_sub = images.add_subparsers(dest='images_command', required=True)
    p = images_sub.add_parser('upload')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--file', required=True)
    p.add_argument('--name')
    p.add_argument('--upload-type')
    p.add_argument('--file-id')
    p.add_argument('--image-signature')
    p.add_argument('--image-url')
    p.set_defaults(func=deps.command_tiktok_media_upload_image)
    p = images_sub.add_parser('info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('image_ids', nargs='+')
    p.set_defaults(func=deps.command_tiktok_images_info)

def add_tiktok_videos_group(parent_subparsers, *, deps) -> None:
    videos = parent_subparsers.add_parser('videos', help='TikTok video asset operations')
    videos_sub = videos.add_subparsers(dest='videos_command', required=True)
    p = videos_sub.add_parser('upload')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--file', required=True)
    p.add_argument('--name')
    p.add_argument('--upload-type')
    p.add_argument('--file-id')
    p.add_argument('--video-id')
    p.add_argument('--video-signature')
    p.add_argument('--video-url')
    p.add_argument('--auto-bind-enabled', action='store_true', default=None)
    p.add_argument('--auto-fix-enabled', action='store_true', default=None)
    p.add_argument('--flaw-detect', action='store_true', default=None)
    p.add_argument('--is-third-party', action='store_true', default=None)
    p.set_defaults(func=deps.command_tiktok_media_upload_video)
    p = videos_sub.add_parser('info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('video_ids', nargs='+')
    p.set_defaults(func=deps.command_tiktok_videos_info)
    p = videos_sub.add_parser('search')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--video-id', dest='video_ids', action='append')
    p.add_argument('--material-id', dest='material_ids', action='append')
    p.add_argument('--displayable', action='store_true', default=None)
    p.add_argument('--width', type=int)
    p.add_argument('--height', type=int)
    p.add_argument('--ratio-json')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_videos_search)

def add_tiktok_aigc_group(parent_subparsers, *, deps) -> None:
    aigc = parent_subparsers.add_parser('aigc', help='TikTok AIGC helpers: voices, image-to-video, product-video, and digital avatars', description='TikTok AIGC capability map:\n- voices: list reusable voice assets from /creative/aigc/voice/get/.\n- image-animation: image-to-video generation via /creative/aigc/image_animation/task/create/.\n- video: product-video tasks via /creative/aigc/video/task/create/ for VOICEOVER, AVATAR_PRODUCT, and TRYON.\n- digital-avatar: standalone avatar assets and avatar video tasks via /creative/digital_avatar/*.\nUse image-animation when you start from images, use video when you are composing product_video_info flows, and use digital-avatar when you need a talking avatar script-driven video.')
    aigc_sub = aigc.add_subparsers(dest='aigc_command', required=True)
    p = aigc_sub.add_parser('voices', help='List reusable AIGC voice assets', description='List reusable voice assets from /creative/aigc/voice/get/. Use this before VOICEOVER or digital-avatar when you need to choose a voice_id.')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--voice-id', dest='voice_ids', action='append')
    p.add_argument('--language')
    p.add_argument('--gender')
    p.add_argument('--speaker-type')
    p.add_argument('--tag-type')
    p.add_argument('--tag-name', dest='tag_names', action='append')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_aigc_voices_list)
    image_animation = aigc_sub.add_parser('image-animation', help='Image-to-video generation from /creative/aigc/image_animation/task/create/', description='Image-to-video flow backed by /creative/aigc/image_animation/task/create/ and the shared /creative/aigc/video/task/list/ + /creative/aigc/video/list/ polling endpoints. Use this when the source material is one image and you want short animated clips.')
    image_animation_sub = image_animation.add_subparsers(dest='image_animation_command', required=True)
    p = image_animation_sub.add_parser('create', help='Create image-to-video tasks from one image URL', description='Create image-to-video tasks from one image using /creative/aigc/image_animation/task/create/.', epilog='Example:\n  motata tiktok aigc image-animation create \\\n    --advertiser-id 123 \\\n    --access-token "$TOKEN" \\\n    --image-url "https://example.com/hero.jpg" \\\n    --animation-prompt "Product demo" \\\n    --provider-model GOKU', formatter_class=argparse.RawTextHelpFormatter)
    deps.add_tiktok_auth_arguments(p)
    deps.add_tiktok_image_animation_create_arguments(p)
    p.set_defaults(func=deps.command_tiktok_aigc_image_animation_create)
    p = image_animation_sub.add_parser('tasks', help='Get image-animation task status by task_id', description='Check image-animation task status through /creative/aigc/video/task/list/ with aigc_video_type=IMAGE_ANIMATION.')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--task-id', dest='task_ids', action='append', required=True)
    p.add_argument('--status')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_aigc_image_animation_tasks)
    p = image_animation_sub.add_parser('list', help='List generated image-animation videos', description='List generated image-animation videos through /creative/aigc/video/list/ with aigc_video_types=[IMAGE_ANIMATION].')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--task-id', dest='task_ids', action='append')
    p.add_argument('--video-id', dest='video_ids', action='append')
    p.add_argument('--status')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_aigc_image_animation_list)
    video = aigc_sub.add_parser('video', help='Product-video AIGC tasks from /creative/aigc/video/task/create/', description="Product-video tasks backed by /creative/aigc/video/task/create/. Use this for VOICEOVER, AVATAR_PRODUCT, and TRYON, all of which use TikTok's product_video_info payload shape.")
    video_sub = video.add_subparsers(dest='aigc_video_command', required=True)
    p = video_sub.add_parser('create', help='Create VOICEOVER, AVATAR_PRODUCT, or TRYON tasks', description='Create product-video tasks through /creative/aigc/video/task/create/. VOICEOVER adds narration to input videos or images, AVATAR_PRODUCT combines product inputs with a real avatar, and TRYON uses product images for try-on generation.', epilog='Example:\n  motata tiktok aigc video create \\\n    --advertiser-id 123 \\\n    --access-token "$TOKEN" \\\n    --type VOICEOVER \\\n    --product-url "https://shop.example.com/products/demo" \\\n    --input-video-id v10033g50000demo123\n\nNote: --input-video-id expects a video_id, not a task_id.', formatter_class=argparse.RawTextHelpFormatter)
    deps.add_tiktok_auth_arguments(p)
    deps.add_tiktok_product_video_create_arguments(p)
    p.set_defaults(func=deps.command_tiktok_aigc_video_create)
    p = video_sub.add_parser('tasks', help='Get product-video task status by type and task_id', description='Check VOICEOVER, AVATAR_PRODUCT, TRYON, or other AIGC video task status through /creative/aigc/video/task/list/.')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--type', dest='aigc_video_type', choices=deps.TIKTOK_AIGC_VIDEO_TYPE_CHOICES, required=True)
    deps.add_filtering_arguments(p)
    p.add_argument('--task-id', dest='task_ids', action='append', required=True)
    p.add_argument('--status')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_aigc_video_tasks)
    p = video_sub.add_parser('list', help='List generated AIGC videos by type', description='List generated product-video outputs through /creative/aigc/video/list/ filtered by aigc_video_type.')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--type', dest='aigc_video_type', choices=deps.TIKTOK_AIGC_VIDEO_TYPE_CHOICES, required=True)
    deps.add_filtering_arguments(p)
    p.add_argument('--task-id', dest='task_ids', action='append')
    p.add_argument('--video-id', dest='video_ids', action='append')
    p.add_argument('--status')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_aigc_video_list)
    digital_avatar = aigc_sub.add_parser('digital-avatar', help='Standalone talking-avatar assets and tasks from /creative/digital_avatar/*', description='Standalone digital-avatar flow backed by /creative/digital_avatar/get/, /creative/digital_avatar/video/task/create/, /creative/digital_avatar/video/task/get/, and /creative/digital_avatar/video/list/. Use this when you need a scripted talking avatar video, not the product_video_info flow.')
    digital_avatar_sub = digital_avatar.add_subparsers(dest='digital_avatar_command', required=True)
    p = digital_avatar_sub.add_parser('list', help='List available digital avatar assets', description='List available avatar assets from /creative/digital_avatar/get/ before creating avatar videos.')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--avatar-id', dest='avatar_ids', action='append')
    p.add_argument('--identity', choices=deps.TIKTOK_DIGITAL_AVATAR_IDENTITY_CHOICES)
    p.add_argument('--keyword')
    p.add_argument('--tag-groups-json')
    p.add_argument('--tag-type')
    p.add_argument('--tag', dest='tags', action='append')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_digital_avatars_list)
    p = digital_avatar_sub.add_parser('task-create', help='Create a standalone digital avatar talking video', description="Create a standalone avatar talking video through /creative/digital_avatar/video/task/create/.\nCLI flags map into TikTok's material_packages[] shape.", epilog='Example:\n  motata tiktok aigc digital-avatar task-create \\\n    --advertiser-id 123 \\\n    --access-token "$TOKEN" \\\n    --avatar-id 7301881390801371138 \\\n    --script "Introduce the product in a short upbeat tone."', formatter_class=argparse.RawTextHelpFormatter)
    deps.add_tiktok_auth_arguments(p)
    deps.add_tiktok_digital_avatar_create_arguments(p)
    p.set_defaults(func=deps.command_tiktok_digital_avatar_task_create)
    p = digital_avatar_sub.add_parser('task-get', help='Get digital avatar task status', description='Get digital avatar task status from /creative/digital_avatar/video/task/get/ with fallback checking against video/list.')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('task_id')
    p.set_defaults(func=deps.command_tiktok_digital_avatar_task_get)
    p = digital_avatar_sub.add_parser('videos', help='List generated digital avatar videos', description='List generated digital avatar videos from /creative/digital_avatar/video/list/.')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--task-id', dest='task_ids', action='append')
    p.add_argument('--avatar-video-id', dest='avatar_video_ids', action='append')
    p.add_argument('--avatar-id')
    p.add_argument('--status')
    p.add_argument('--start-date')
    p.add_argument('--end-date')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_digital_avatar_video_list)
    p = digital_avatar_sub.add_parser('rename-video', help='Rename a generated digital avatar video', description='Rename a generated avatar video through /file/video/ad/update/ using avatar_video_id and file_name.')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--avatar-video-id', required=True)
    p.add_argument('--file-name', required=True)
    p.set_defaults(func=deps.command_tiktok_digital_avatar_video_rename)

def add_tiktok_assets_group(parent_subparsers, *, deps) -> None:
    assets = parent_subparsers.add_parser('assets', help='TikTok creative asset helpers')
    assets_sub = assets.add_subparsers(dest='assets_command', required=True)
    p = assets_sub.add_parser('image-info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('image_ids', nargs='+')
    p.set_defaults(func=deps.command_tiktok_images_info)
    p = assets_sub.add_parser('video-info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('video_ids', nargs='+')
    p.set_defaults(func=deps.command_tiktok_videos_info)
    p = assets_sub.add_parser('video-search')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--video-id', dest='video_ids', action='append')
    p.add_argument('--material-id', dest='material_ids', action='append')
    p.add_argument('--displayable', action='store_true', default=None)
    p.add_argument('--width', type=int)
    p.add_argument('--height', type=int)
    p.add_argument('--ratio-json')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_videos_search)
    p = assets_sub.add_parser('delete')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_assets_delete)
    p = assets_sub.add_parser('share')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_assets_share)
    p = assets_sub.add_parser('discover')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--bc-id', dest='bc_ids', action='append')
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--catalog-page-size', type=int, default=20)
    p.add_argument('--include-catalog-bindings', action='store_true')
    p.add_argument('--skip-catalogs', action='store_true')
    p.set_defaults(func=deps.command_tiktok_assets_discover)
    p = assets_sub.add_parser('cta-list')
    p.add_argument('--type', choices=['aco', 'smart-plus', 'all'], default='all', help='CTA type: aco (regular ads), smart-plus (Smart Plus ads), or all')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_cta_list)

def add_tiktok_validate_common_arguments(parser: argparse.ArgumentParser, *, deps) -> None:
    deps.add_payload_arguments(parser)
    parser.add_argument('--smart-plus', action='store_true')
    parser.add_argument('--identity-id')
    parser.add_argument('--identity-type')
    parser.add_argument('--identity-authorized-bc-id')
    parser.add_argument('--video-id')
    parser.add_argument('--image-id', dest='image_ids', action='append')
    parser.add_argument('--image-web-uri', dest='image_web_uris', action='append')
    parser.add_argument('--landing-page-url', dest='landing_page_urls', action='append')
    parser.add_argument('--tracking-app-id')
    parser.add_argument('--tracking-pixel-id')
    parser.add_argument('--tracking-offline-event-set-id', dest='tracking_offline_event_set_ids', action='append')

def add_tiktok_validate_group(parent_subparsers, *, deps) -> None:
    validate = parent_subparsers.add_parser('validate', help='TikTok preflight validation helpers')
    validate_sub = validate.add_subparsers(dest='validate_command', required=True)
    p = validate_sub.add_parser('creative')
    deps.add_tiktok_auth_arguments(p)
    add_tiktok_validate_common_arguments(p, deps=deps)
    p.set_defaults(func=deps.command_tiktok_validate_creative)
    p = validate_sub.add_parser('ad-link')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--adgroup-id', required=True)
    add_tiktok_validate_common_arguments(p, deps=deps)
    p.set_defaults(func=deps.command_tiktok_validate_ad_link)
    p = validate_sub.add_parser('promoted-object')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.add_argument('--smart-plus', action='store_true')
    p.add_argument('--campaign-id')
    p.add_argument('--adgroup-id')
    p.add_argument('--objective-type')
    p.add_argument('--promotion-type')
    p.add_argument('--optimization-goal')
    p.add_argument('--optimization-event')
    p.add_argument('--placement', dest='placements', action='append')
    p.add_argument('--pixel-id')
    p.add_argument('--app-id')
    p.add_argument('--store-id')
    p.add_argument('--catalog-id')
    p.add_argument('--landing-page-url')
    p.add_argument('--app-promotion-type')
    p.add_argument('--campaign-type')
    p.add_argument('--bc-id', dest='bc_ids', action='append')
    p.set_defaults(func=deps.command_tiktok_validate_promoted_object)

def add_tiktok_accounts_group(parent_subparsers, *, deps) -> None:
    accounts = parent_subparsers.add_parser('accounts', help='TikTok advertiser account operations')
    accounts_sub = accounts.add_subparsers(dest='accounts_command', required=True)
    p = accounts_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('advertiser_ids', nargs='*')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_accounts_list)
    p = accounts_sub.add_parser('info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('advertiser_ids', nargs='*')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_accounts_info)
    p = accounts_sub.add_parser('inspect')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('advertiser_ids', nargs='*')
    p.add_argument('--fields', nargs='*')
    p.set_defaults(func=deps.command_tiktok_accounts_inspect)
    p = accounts_sub.add_parser('update')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_accounts_update)

def add_tiktok_activities_group(parent_subparsers, *, deps) -> None:
    activities = parent_subparsers.add_parser('activities', aliases=['activity'], help='TikTok changelog activity operations')
    activities_sub = activities.add_subparsers(dest='activities_command', required=True)
    p = activities_sub.add_parser('get', help='Create and optionally poll a changelog task for advertiser activities')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--since', '--start-date', dest='start_date')
    p.add_argument('--until', '--end-date', dest='end_date')
    p.add_argument('--timezone')
    p.add_argument('--module', choices=['BIDDING_AND_OPTIMIZATION', 'BUDGET', 'STATUS', 'TARGETING'])
    p.add_argument('--object-type', choices=['AD', 'ADGROUP', 'ADVERTISER', 'CAMPAIGN', 'INSTANT_FORM'])
    p.add_argument('--object-ids', nargs='+')
    p.add_argument('--operation-types', nargs='+', help='Operation types. Accepts space-separated values or comma-separated strings: CREATE,AUDIT,STATUS,UPDATE,DELETE,DOWNLOAD_LEADS,SUBSCRIBE_FORM,UNSUBSCRIBE_FORM.')
    p.add_argument('--order-fields', nargs='+')
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--no-wait', action='store_true', help='Return after task creation without polling.')
    p.add_argument('--timeout-seconds', type=int, default=60)
    p.add_argument('--poll-seconds', type=float, default=5.0)
    p.set_defaults(func=deps.command_tiktok_activities_get)

def add_tiktok_auth_group(parent_subparsers, *, deps) -> None:
    auth = parent_subparsers.add_parser('auth', help='TikTok authentication helpers')
    auth_sub = auth.add_subparsers(dest='auth_command', required=True)
    p = auth_sub.add_parser('advertisers')
    p.add_argument('--app-id', required=True)
    p.add_argument('--secret', required=True)
    p.add_argument('--access-token', required=True)
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_auth_advertisers)

def add_tiktok_targeting_group(parent_subparsers, *, deps) -> None:
    targeting = parent_subparsers.add_parser('targeting', help='TikTok targeting helpers')
    targeting_sub = targeting.add_subparsers(dest='targeting_command', required=True)
    p = targeting_sub.add_parser('regions')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--language')
    p.set_defaults(func=deps.command_tiktok_targeting_regions)
    p = targeting_sub.add_parser('search')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_targeting_search)
    p = targeting_sub.add_parser('info')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_targeting_info)
    p = targeting_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--location-id', dest='location_ids', action='append', required=True)
    p.add_argument('--scene', required=True)
    p.set_defaults(func=deps.command_tiktok_targeting_list)

def add_tiktok_identities_group(parent_subparsers, *, deps) -> None:
    identities = parent_subparsers.add_parser('identities', help='TikTok identity asset operations')
    identities_sub = identities.add_subparsers(dest='identities_command', required=True)
    p = identities_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--identity-type')
    p.add_argument('--identity-authorized-bc-id')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_identities_list)
    p = identities_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_identities_create)
    p = identities_sub.add_parser('video-info')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--identity-type', required=True)
    p.add_argument('--identity-id', required=True)
    p.add_argument('--identity-authorized-bc-id')
    p.add_argument('--item-id')
    p.add_argument('--item-ids', dest='item_ids', action='append', help='Repeatable item_id. Max 20 per TikTok API request.')
    p.add_argument('--item-type', choices=['VIDEO', 'CAROUSEL'], default='VIDEO')
    p.set_defaults(func=deps.command_tiktok_identities_video_info)

def add_tiktok_insights_group(parent_subparsers, *, deps) -> None:
    insights = parent_subparsers.add_parser('insights', help='TikTok reporting and insights')
    insights_sub = insights.add_subparsers(dest='insights_command', required=True)
    p = insights_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--report-type', required=True)
    p.add_argument('--query-mode')
    p.add_argument('--advertiser', dest='advertiser_ids', action='append')
    p.add_argument('--bc-id')
    p.add_argument('--service-type')
    p.add_argument('--data-level')
    p.add_argument('--dimension', dest='dimensions', action='append')
    p.add_argument('--metric', dest='metrics', action='append')
    p.add_argument('--start-date')
    p.add_argument('--end-date')
    p.add_argument('--order-field')
    p.add_argument('--order-type')
    p.add_argument('--filtering-json')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.add_argument('--enable-total-metrics', action='store_true', default=None)
    p.add_argument('--multi-adv-report-in-utc-time', action='store_true', default=None)
    p.add_argument('--query-lifetime', action='store_true', default=None)
    p.set_defaults(func=deps.command_tiktok_insights_get)
    p = insights_sub.add_parser('smartplus-overview')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--dimension', dest='dimensions', action='append', required=True)
    p.add_argument('--metric', dest='metrics', action='append')
    p.add_argument('--start-date')
    p.add_argument('--end-date')
    p.add_argument('--query-lifetime', action='store_true', default=None)
    p.add_argument('--sort-field')
    p.add_argument('--sort-type')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_insights_smartplus_overview)
    p = insights_sub.add_parser('smartplus-breakdown')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--dimension', dest='dimensions', action='append', required=True)
    p.add_argument('--metric', dest='metrics', action='append')
    p.add_argument('--start-date', required=True)
    p.add_argument('--end-date', required=True)
    p.add_argument('--sort-field')
    p.add_argument('--sort-type')
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_insights_smartplus_breakdown)

def add_tiktok_landing_pages_group(parent_subparsers, *, deps) -> None:
    landing_pages = parent_subparsers.add_parser('landing-pages', aliases=['landing-page', 'landings'], help='TikTok landing page spend analysis')
    landing_pages_sub = landing_pages.add_subparsers(dest='landing_pages_command', required=True)
    p = landing_pages_sub.add_parser('analyze')
    p.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_ids', action='append', help='TikTok advertiser ID. Repeat for multiple advertisers.')
    p.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    p.add_argument('--app-id', default=deps.os.environ.get('TIKTOK_APP_ID'))
    p.add_argument('--secret', default=deps.os.environ.get('TIKTOK_APP_SECRET'))
    p.add_argument('--start-date', '--since', dest='start_date')
    p.add_argument('--end-date', '--until', dest='end_date')
    p.add_argument('--top', type=int)
    p.add_argument('--ad-limit', type=int, help='Analyze only the top spend ads returned by the TikTok report.')
    p.add_argument('--advertiser-limit', type=int, default=10, help='Top spend auto-discovered advertisers to analyze.')
    p.add_argument('--page-size', type=int, default=1000, help='TikTok ad report page size.')
    p.add_argument('--max-pages', type=int, default=50, help='Maximum TikTok report pages per advertiser.')
    p.add_argument('--no-product', dest='no_product', action='store_true', default=True, help='Skip product page scraping/enrichment. This is the default.')
    p.add_argument('--product', dest='no_product', action='store_false', help='Enable product page scraping/enrichment.')
    p.add_argument('--product-limit', type=int, default=50, help='Maximum ranked landing pages to product-enrich.')
    p.add_argument('--include-ads', action='store_true', help='Include all ads under each landing page group.')
    p.add_argument('--smart-plus', action='store_true', help='Resolve SmartPlus ad details instead of normal ads.')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_landing_pages_analyze)

def add_tiktok_apps_group(parent_subparsers, *, deps) -> None:
    apps = parent_subparsers.add_parser('apps', aliases=['app-discovery'], help='TikTok active app discovery from campaign, adgroup, and ad attributes')
    apps_sub = apps.add_subparsers(dest='apps_command', required=True)
    p = apps_sub.add_parser('analyze')
    p.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_ids', action='append', help='TikTok advertiser ID. Repeat for multiple advertisers.')
    p.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    p.add_argument('--start-date', '--since', dest='start_date')
    p.add_argument('--end-date', '--until', dest='end_date')
    p.add_argument('--advertiser-limit', type=int, default=2, help='Auto-discovered advertiser limit.')
    p.add_argument('--campaign-limit', type=int, default=20, help='Top spend campaigns to probe per advertiser.')
    p.add_argument('--include-campaigns', action='store_true', help='Include campaign-level app evidence under each app group.')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_apps_analyze)

def add_tiktok_user_type_group(parent_subparsers, *, deps) -> None:
    user_type = parent_subparsers.add_parser('user-type', aliases=['customer-type', 'account-type', 'classify-user'], help='Classify TikTok advertiser vertical from top-spend campaigns, landing pages, and app evidence')
    user_type_sub = user_type.add_subparsers(dest='user_type_command', required=True)
    p = user_type_sub.add_parser('analyze')
    p.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_ids', action='append', help='TikTok advertiser ID. Repeat for multiple advertisers.')
    p.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    p.add_argument('--start-date', '--since', dest='start_date')
    p.add_argument('--end-date', '--until', dest='end_date')
    p.add_argument('--advertiser-limit', type=int, default=10, help='Auto-discovered advertiser limit.')
    p.add_argument('--campaign-limit', type=int, default=10, help='Top spend campaigns to analyze per advertiser.')
    p.add_argument('--ad-limit', type=int, default=5, help='Top spend ads to inspect for landing URLs.')
    p.add_argument('--content-limit', type=int, default=60, help='Maximum landing/app-store URLs to scrape for classification.')
    p.add_argument('--page-size', type=int, default=1000, help='TikTok ad report page size.')
    p.add_argument('--max-pages', type=int, default=50, help='Maximum TikTok report pages per advertiser.')
    p.add_argument('--smart-plus', action='store_true', help='Resolve SmartPlus ad details for landing URLs.')
    p.add_argument('--include-evidence', action='store_true', help='Include matched text snippets and scraped content details.')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_user_type_analyze)

def add_tiktok_metrics_group(parent_subparsers, *, deps) -> None:
    metrics = parent_subparsers.add_parser('metrics', help='TikTok metric probe helpers')
    metrics_sub = metrics.add_subparsers(dest='metrics_command', required=True)
    p = metrics_sub.add_parser('probe')
    p.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_ids', action='append', help='TikTok advertiser ID. Repeat for multiple advertisers.')
    p.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    p.add_argument('--start-date', '--since', dest='start_date')
    p.add_argument('--end-date', '--until', dest='end_date')
    p.add_argument('--advertiser-limit', type=int, default=10, help='Top spend auto-discovered advertisers to probe.')
    p.add_argument('--page-size', type=int, default=5, help='Per metric-group report page size.')
    p.add_argument('--group', dest='groups', action='append', help='Probe only this metric group. Repeat for multiple groups.')
    p.add_argument('--profile', choices=['light', 'batch', 'vertical', 'full'], default='batch', help='Probe profile. batch avoids high-risk gated groups such as TikTok web_events; full is for connector QA.')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_metrics_probe)

def add_tiktok_audience_group(parent_subparsers, *, deps) -> None:
    audience = parent_subparsers.add_parser('audience', aliases=['audience-breakdown'], help='TikTok audience, geo, placement, and device breakdown diagnostics')
    audience_sub = audience.add_subparsers(dest='audience_command', required=True)
    p = audience_sub.add_parser('breakdown')
    p.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_id', required=True)
    p.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    p.add_argument('--json', action='store_true', default=True)
    p.add_argument('--start-date', '--since', dest='start_date')
    p.add_argument('--end-date', '--until', dest='end_date')
    p.add_argument('--breakdown', dest='breakdowns', action='append', choices=['country', 'age_gender', 'placement', 'device'], help='Audience lens to fetch. Repeat to limit the run; defaults to all key lenses.')
    p.add_argument('--data-level', default='AUCTION_ADVERTISER')
    p.add_argument('--top', type=int, default=20, help='Maximum segments kept per breakdown.')
    p.add_argument('--page-size', type=int, default=500, help='Per-breakdown report page size.')
    p.set_defaults(func=deps.command_tiktok_audience_breakdown)

def add_tiktok_creative_retention_report_arguments(parser: argparse.ArgumentParser, *, deps) -> None:
    parser.add_argument('--advertiser-id', '--account-id', '--account', '--advertiser', dest='advertiser_id', required=True)
    parser.add_argument('--access-token', default=deps.os.environ.get('TIKTOK_ACCESS_TOKEN') or deps.os.environ.get('MOTATA_TIKTOK_ACCESS_TOKEN'))
    parser.add_argument('--json', action='store_true', default=True)
    parser.add_argument('--start-date', '--since', dest='start_date')
    parser.add_argument('--end-date', '--until', dest='end_date')
    parser.add_argument('--top', type=int, default=20, help='Number of creatives kept in each ranking section.')
    parser.add_argument('--page-size', type=int, default=200, help='Ad-level report page size.')
    parser.add_argument('--max-pages', type=int, default=3, help='Maximum report pages to scan.')
    parser.add_argument('--ad-id', dest='ad_ids', action='append', help='Limit retention and preview enrichment to one final report ad ID. Repeatable.')
    parser.add_argument('--ad-ids', dest='ad_ids_csv', help='Comma-separated final report ad IDs for targeted retention and preview enrichment.')
    parser.add_argument('--no-attributes', action='store_true', default=False, help='Skip TikTok attribute metrics such as ad_name.')
    parser.add_argument('--no-previews', action='store_true', default=False, help='Skip ad/creative preview image and URL enrichment.')
    parser.add_argument('--no-probe-on-missing-core', action='store_true', default=False, help='Do not run a full metric probe when core metrics, especially revenue, are missing.')
    parser.set_defaults(func=deps.command_tiktok_creative_retention_report)

def add_tiktok_creatives_group(parent_subparsers, *, deps) -> None:
    creatives = parent_subparsers.add_parser('creatives', help='TikTok creative portfolio and text helpers')
    creatives_sub = creatives.add_subparsers(dest='creatives_command', required=True)
    p = creatives_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    deps.add_filtering_arguments(p)
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_creatives_list)
    p = creatives_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('creative_portfolio_id')
    p.set_defaults(func=deps.command_tiktok_creatives_get)
    p = creatives_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creatives_create)
    p = creatives_sub.add_parser('share-link')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creatives_share_link)
    p = creatives_sub.add_parser('smart-text')
    deps.add_tiktok_auth_arguments(p)
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creatives_smart_text)
    p = creatives_sub.add_parser('retention-report', aliases=['creative-retention'], help='Short-drama creative retention curve ranking')
    add_tiktok_creative_retention_report_arguments(p, deps=deps)

def add_tiktok_items_group(parent_subparsers, *, deps) -> None:
    items = parent_subparsers.add_parser('items', aliases=['item', 'posts', 'post'], help='Public TikTok post/item metadata resolver')
    items_sub = items.add_subparsers(dest='items_command', required=True)
    p = items_sub.add_parser('resolve', aliases=['get'], help='Resolve item IDs to real handle, username, preview, avatar, URL, and upload time')
    p.add_argument('item_ids', nargs='+', type=deps.item_id_from_value, help='TikTok item IDs or video URLs')
    p.add_argument('--timeout', type=int, default=30, help='HTTP timeout in seconds')
    p.add_argument('--workers', type=int, default=1, help='Concurrent workers for multiple item IDs')
    p.add_argument('--download-dir', help='Optional directory for avatar and preview images')
    p.add_argument('--save-html-dir', help='Optional directory for raw HTML debugging')
    p.add_argument('--include-timing', action='store_true', help='Include per-item elapsed_seconds')
    p.add_argument('--out', help='Optional JSON output path')
    p.add_argument('--json', action='store_true', default=True)
    p.set_defaults(func=deps.command_tiktok_items_resolve)

def add_tiktok_creative_retention_group(parent_subparsers, *, deps) -> None:
    creative_retention = parent_subparsers.add_parser('creative-retention', aliases=['retention'], help='TikTok short-drama creative retention reports')
    creative_retention_sub = creative_retention.add_subparsers(dest='creative_retention_command', required=True)
    p = creative_retention_sub.add_parser('report')
    add_tiktok_creative_retention_report_arguments(p, deps=deps)

def add_tiktok_creative_assets_group(parent_subparsers, *, deps) -> None:
    creative_assets = parent_subparsers.add_parser('creative-assets', aliases=['creative-asset'], help='Unified TikTok CreativeManagementApi helpers')
    creative_assets_sub = creative_assets.add_subparsers(dest='creative_assets_command', required=True)
    portfolio = creative_assets_sub.add_parser('portfolio', help='Creative portfolio operations')
    portfolio_sub = portfolio.add_subparsers(dest='portfolio_command', required=True)
    p = portfolio_sub.add_parser('list')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--creative-portfolio-id', dest='creative_portfolio_ids', action='append')
    p.add_argument('--creative-portfolio-type', dest='creative_portfolio_types', action='append')
    p.add_argument('--title')
    p.add_argument('--query')
    p.add_argument('--page', type=int, default=1)
    p.add_argument('--page-size', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_list)
    p = portfolio_sub.add_parser('get')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('creative_portfolio_id')
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_get)
    p = portfolio_sub.add_parser('create')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--creative-portfolio-type')
    p.add_argument('--portfolio-content-json')
    p.add_argument('--portfolio-content-file')
    p.add_argument('--title')
    p.add_argument('--ad-text')
    p.add_argument('--asset-content')
    p.add_argument('--primary-text')
    p.add_argument('--secondary-text')
    p.add_argument('--description')
    p.add_argument('--content-url')
    p.add_argument('--card-type')
    p.add_argument('--app-id')
    p.add_argument('--origin-app-id')
    p.add_argument('--image-id')
    p.add_argument('--jump-image-uri')
    p.add_argument('--thumbnail-id')
    p.add_argument('--video-id')
    p.add_argument('--identity-id')
    p.add_argument('--identity-type')
    p.add_argument('--identity-authorized-bc-id')
    p.add_argument('--call-to-action')
    p.add_argument('--call-to-action-text')
    p.add_argument('--product-source')
    p.add_argument('--product-set-id')
    p.add_argument('--catalog-id')
    p.add_argument('--catalog-authorized-bc-id')
    p.add_argument('--store-id')
    p.add_argument('--store-authorized-bc-id')
    p.add_argument('--category-label')
    p.add_argument('--product-platform-id')
    p.add_argument('--product-specific-type')
    p.add_argument('--card-show-price', action='store_true', default=None)
    p.add_argument('--card-image-index', type=int)
    p.add_argument('--display-price-enabled', action='store_true', default=None)
    p.add_argument('--enable-image-optimization', action='store_true', default=None)
    p.add_argument('--gesture-type', type=int)
    p.add_argument('--interactive-music-id')
    p.add_argument('--vertical-creative-strategy', type=int)
    p.add_argument('--vertical-video-strategy', type=int)
    p.add_argument('--slide-length', type=int)
    p.add_argument('--advanced-show-time', type=int)
    p.add_argument('--advanced-interact-type', type=int)
    p.add_argument('--advanced-interact-shape', type=int)
    p.add_argument('--asset-id', dest='asset_ids', action='append')
    p.add_argument('--sku-id', dest='sku_ids', action='append')
    p.add_argument('--item-group-id', dest='item_group_ids', action='append')
    p.add_argument('--tag', dest='tags', action='append')
    p.add_argument('--card-tag', dest='card_tags', action='append')
    p.add_argument('--selling-point', dest='selling_points', action='append')
    p.add_argument('--country-code', dest='country_codes', action='append')
    p.add_argument('--layout', dest='layouts', action='append')
    p.add_argument('--advanced-audio-video-id')
    p.add_argument('--advanced-gesture-icon-image-id')
    p.add_argument('--advanced-gesture-image-image-id')
    p.add_argument('--advanced-audio-info-json')
    p.add_argument('--advanced-audio-info-file')
    p.add_argument('--advanced-gesture-icon-json')
    p.add_argument('--advanced-gesture-icon-file')
    p.add_argument('--advanced-gesture-image-json')
    p.add_argument('--advanced-gesture-image-file')
    p.add_argument('--advanced-image-info-json')
    p.add_argument('--advanced-image-info-file')
    p.add_argument('--advanced-position-json')
    p.add_argument('--advanced-position-file')
    p.add_argument('--badge-image-info-json')
    p.add_argument('--badge-image-info-file')
    p.add_argument('--sticker-param-json')
    p.add_argument('--sticker-param-file')
    p.add_argument('--slide-dimension-json')
    p.add_argument('--slide-dimension-file')
    p.add_argument('--showcase-products-json')
    p.add_argument('--showcase-products-file')
    p.add_argument('--context-info-json')
    p.add_argument('--context-info-file')
    p.add_argument('--context-app-id')
    p.add_argument('--context-core-user-id')
    p.add_argument('--context-developer-id')
    p.add_argument('--context-x-forwarded-for')
    p.add_argument('--context-x-real-ip')
    p.add_argument('--context-user-agent')
    p.add_argument('--context-referer')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_create)
    p = portfolio_sub.add_parser('select')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--creative-portfolio-id', dest='creative_portfolio_ids', action='append')
    p.add_argument('--creative-portfolio-type', dest='creative_portfolio_types', action='append')
    p.add_argument('--title')
    p.add_argument('--query')
    p.add_argument('--limit', type=int, default=10)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--max-pages', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_select)
    p = portfolio_sub.add_parser('inspect')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--creative-portfolio-id', dest='creative_portfolio_ids', action='append')
    p.add_argument('--creative-portfolio-type', dest='creative_portfolio_types', action='append')
    p.add_argument('--title')
    p.add_argument('--query')
    p.add_argument('--limit', type=int, default=10)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--max-pages', type=int, default=20)
    p.add_argument('--include-raw', action='store_true', default=False)
    p.add_argument('--output-file')
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_inspect)
    p = portfolio_sub.add_parser('export')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--output-file', required=True)
    p.add_argument('--creative-portfolio-id', dest='creative_portfolio_ids', action='append')
    p.add_argument('--creative-portfolio-type', dest='creative_portfolio_types', action='append')
    p.add_argument('--title')
    p.add_argument('--query')
    p.add_argument('--limit', type=int, default=10)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--max-pages', type=int, default=20)
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_export)
    p = portfolio_sub.add_parser('match-campaign')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--campaign-id', required=True)
    p.add_argument('--smart-plus', action='store_true')
    p.add_argument('--limit', type=int, default=10)
    p.add_argument('--page-size', type=int, default=100)
    p.add_argument('--max-pages', type=int, default=20)
    p.add_argument('--output-file')
    p.set_defaults(func=deps.command_tiktok_creative_assets_portfolio_match_campaign)
    asset = creative_assets_sub.add_parser('asset', help='Creative asset delete/share helpers')
    asset_sub = asset.add_subparsers(dest='asset_command', required=True)
    p = asset_sub.add_parser('delete')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--image-id', dest='image_ids', action='append')
    p.add_argument('--video-id', dest='video_ids', action='append')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creative_assets_delete)
    p = asset_sub.add_parser('share')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--material-id', dest='material_ids', action='append')
    p.add_argument('--shared-advertiser-id', dest='shared_advertiser_ids', action='append')
    p.add_argument('--asset-type', choices=['VIDEO', 'IMAGE', 'MUSIC'])
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creative_assets_share)
    p = creative_assets_sub.add_parser('share-link', help='Create shareable links for creative assets')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--shared-assets-json')
    p.add_argument('--shared-assets-file')
    p.add_argument('--sharer')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creative_assets_share_link)
    p = creative_assets_sub.add_parser('smart-text', help='Generate smart text suggestions')
    deps.add_tiktok_auth_arguments(p)
    p.add_argument('--adgroup-id')
    p.add_argument('--industry-id')
    p.add_argument('--keyword', dest='keywords', action='append')
    p.add_argument('--language')
    p.add_argument('--limit', type=int, default=10)
    p.add_argument('--param-type', default='CUSTOMIZED')
    deps.add_payload_arguments(p)
    p.set_defaults(func=deps.command_tiktok_creative_assets_smart_text)

def register_tiktok_commands(subparsers, *, deps) -> None:
    tiktok = subparsers.add_parser('tiktok', help='TikTok Business API operations')
    tiktok_sub = tiktok.add_subparsers(dest='tiktok_command', required=True)
    add_tiktok_auth_group(tiktok_sub, deps=deps)
    add_tiktok_accounts_group(tiktok_sub, deps=deps)
    add_tiktok_activities_group(tiktok_sub, deps=deps)
    add_tiktok_campaign_group(tiktok_sub, name='campaigns', smart_plus=False, help_text='Normal TikTok campaigns', deps=deps)
    add_tiktok_campaign_group(tiktok_sub, name='smartplus-campaigns', smart_plus=True, help_text='TikTok SmartPlus campaigns', deps=deps)
    add_tiktok_gmv_max_campaign_group(tiktok_sub, deps=deps)
    add_tiktok_gmv_max_video_group(tiktok_sub, deps=deps)
    add_tiktok_gmv_max_custom_anchor_video_group(tiktok_sub, deps=deps)
    add_tiktok_gmv_max_product_group(tiktok_sub, deps=deps)
    add_tiktok_gmv_max_report_group(tiktok_sub, deps=deps)
    add_tiktok_adgroup_group(tiktok_sub, name='adgroups', smart_plus=False, help_text='Normal TikTok ad groups', deps=deps)
    add_tiktok_adgroup_group(tiktok_sub, name='smartplus-adgroups', smart_plus=True, help_text='TikTok SmartPlus ad groups', deps=deps)
    add_tiktok_ad_group(tiktok_sub, name='ads', smart_plus=False, help_text='Normal TikTok ads', deps=deps)
    add_tiktok_ad_group(tiktok_sub, name='smartplus-ads', smart_plus=True, help_text='TikTok SmartPlus ads', deps=deps)
    add_tiktok_creatives_group(tiktok_sub, deps=deps)
    add_tiktok_items_group(tiktok_sub, deps=deps)
    add_tiktok_creative_retention_group(tiktok_sub, deps=deps)
    add_tiktok_identities_group(tiktok_sub, deps=deps)
    add_tiktok_targeting_group(tiktok_sub, deps=deps)
    add_tiktok_insights_group(tiktok_sub, deps=deps)
    add_tiktok_landing_pages_group(tiktok_sub, deps=deps)
    add_tiktok_apps_group(tiktok_sub, deps=deps)
    add_tiktok_user_type_group(tiktok_sub, deps=deps)
    add_tiktok_metrics_group(tiktok_sub, deps=deps)
    add_tiktok_audience_group(tiktok_sub, deps=deps)
    add_tiktok_media_group(tiktok_sub, deps=deps)
    add_tiktok_images_group(tiktok_sub, deps=deps)
    add_tiktok_videos_group(tiktok_sub, deps=deps)
    add_tiktok_aigc_group(tiktok_sub, deps=deps)
    add_tiktok_creative_assets_group(tiktok_sub, deps=deps)
    add_tiktok_assets_group(tiktok_sub, deps=deps)
    add_tiktok_validate_group(tiktok_sub, deps=deps)
