from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass(frozen=True)
class MetricSpec:
    platform: str
    metric: str
    label: str
    category: str
    value_type: str = "numeric_string"
    required_level: str | None = None
    dimensions: tuple[str, ...] = ()
    known_constraints: str | None = None
    estimated: bool = False
    deprecated: bool = False
    in_development: bool = False
    user_type_tags: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["dimensions"] = list(self.dimensions)
        payload["user_type_tags"] = list(self.user_type_tags)
        return payload


@dataclass(frozen=True)
class MetricGroup:
    platform: str
    name: str
    metrics: tuple[str, ...]
    category: str
    required_level: str | None = None
    dimensions: tuple[str, ...] = ()
    request_options: dict[str, Any] = field(default_factory=dict)


def metric_map(specs: list[MetricSpec]) -> dict[str, MetricSpec]:
    return {spec.metric: spec for spec in specs}


def _humanize_metric_name(metric: str) -> str:
    return metric.replace("_", " ")


def _specs(
    metric_names: list[str] | tuple[str, ...],
    *,
    category: str,
    value_type: str = "numeric_string",
    required_level: str | None = None,
    dimensions: tuple[str, ...] = (),
    known_constraints: str | None = None,
    estimated: bool = False,
    deprecated: bool = False,
    in_development: bool = False,
    user_type_tags: tuple[str, ...] = (),
) -> list[MetricSpec]:
    return [
        MetricSpec(
            "tiktok",
            metric,
            _humanize_metric_name(metric),
            category,
            value_type,
            required_level,
            dimensions,
            known_constraints,
            estimated,
            deprecated,
            in_development,
            user_type_tags,
        )
        for metric in metric_names
    ]


def _suffix_metrics(base: str, suffixes: tuple[str, ...]) -> list[str]:
    return [f"{base}{suffix}" for suffix in suffixes]


META_METRICS: list[MetricSpec] = [
    MetricSpec("meta", "spend", "消耗", "core", "money", user_type_tags=("all",)),
    MetricSpec("meta", "impressions", "展示", "core", user_type_tags=("all",)),
    MetricSpec("meta", "reach", "覆盖", "core", estimated=True, user_type_tags=("all",)),
    MetricSpec("meta", "clicks", "点击", "core", user_type_tags=("all",)),
    MetricSpec("meta", "cpc", "CPC", "core", "money", user_type_tags=("all",)),
    MetricSpec("meta", "cpm", "CPM", "core", "money", user_type_tags=("all",)),
    MetricSpec("meta", "cpp", "千人覆盖成本", "core", "money", estimated=True, user_type_tags=("all",)),
    MetricSpec("meta", "ctr", "CTR", "core", "rate", user_type_tags=("all",)),
    MetricSpec("meta", "frequency", "频次", "core", estimated=True, user_type_tags=("all",)),
    MetricSpec("meta", "inline_link_clicks", "站内链接点击", "engagement", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "inline_link_click_ctr", "链接点击率", "engagement", "rate", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "cost_per_inline_link_click", "链接点击成本", "engagement", "money", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "outbound_clicks", "出站点击", "engagement", "action_stats", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "outbound_clicks_ctr", "出站点击率", "engagement", "action_stats", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "cost_per_outbound_click", "出站点击成本", "engagement", "action_stats", user_type_tags=("web", "ecommerce", "w2a")),
    MetricSpec("meta", "website_clicks", "网站点击", "engagement", user_type_tags=("web", "ecommerce")),
    MetricSpec("meta", "website_ctr", "网站点击率", "engagement", "action_stats", user_type_tags=("web", "ecommerce")),
    MetricSpec("meta", "actions", "行为", "conversion", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "action_values", "行为价值", "value_roas", "action_stats", user_type_tags=("ecommerce", "app", "game")),
    MetricSpec("meta", "cost_per_action_type", "行为成本", "conversion", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "total_actions", "总行为", "conversion", user_type_tags=("all",)),
    MetricSpec("meta", "total_unique_actions", "去重行为人数", "conversion", estimated=True, user_type_tags=("all",)),
    MetricSpec("meta", "total_action_value", "总行为价值", "value_roas", user_type_tags=("ecommerce", "app", "game")),
    MetricSpec("meta", "cost_per_total_action", "总行为成本", "conversion", "money", user_type_tags=("all",)),
    MetricSpec("meta", "results", "成效", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_result", "成效成本", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "result_rate", "成效率", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "objective_results", "目标成效", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "objective_result_rate", "目标成效率", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_objective_result", "目标成效成本", "conversion", "result_stats", user_type_tags=("all",)),
    MetricSpec("meta", "purchase_roas", "购买 ROAS", "value_roas", "action_stats", user_type_tags=("ecommerce", "app", "game")),
    MetricSpec("meta", "website_purchase_roas", "网站购买 ROAS", "value_roas", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "mobile_app_purchase_roas", "App 购买 ROAS", "value_roas", "action_stats", user_type_tags=("app", "game", "w2a")),
    MetricSpec("meta", "conversion_values", "转化价值", "value_roas", "action_stats", user_type_tags=("ecommerce", "app", "game")),
    MetricSpec("meta", "conversions", "转化", "conversion", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_conversion", "转化成本", "conversion", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "app_store_clicks", "商店点击", "app", user_type_tags=("app", "game", "w2a")),
    MetricSpec("meta", "deeplink_clicks", "Deep Link 点击", "app", user_type_tags=("app", "game", "w2a")),
    MetricSpec("meta", "video_play_actions", "视频播放", "creative_video", "action_stats", in_development=True, user_type_tags=("all",)),
    MetricSpec("meta", "video_continuous_2_sec_watched_actions", "连续 2 秒播放", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_6_sec_watched_actions", "6 秒播放", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_30_sec_watched_actions", "30 秒播放", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_avg_time_watched_actions", "平均观看时长", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_p25_watched_actions", "播放 25%", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_p50_watched_actions", "播放 50%", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_p75_watched_actions", "播放 75%", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_p95_watched_actions", "播放 95%", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_p100_watched_actions", "播放完成", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "video_complete_watched_actions", "完整观看", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_thruplay", "ThruPlay 成本", "creative_video", "action_stats", in_development=True, user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_2_sec_continuous_video_view", "2 秒播放成本", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "cost_per_15_sec_video_view", "15 秒播放成本", "creative_video", "action_stats", user_type_tags=("all",)),
    MetricSpec("meta", "canvas_avg_view_time", "Instant Experience 平均时长", "engagement", user_type_tags=("ecommerce", "lead")),
    MetricSpec("meta", "canvas_avg_view_percent", "Instant Experience 平均浏览比例", "engagement", "rate", user_type_tags=("ecommerce", "lead")),
    MetricSpec("meta", "instant_experience_clicks_to_open", "Instant Experience 打开点击", "engagement", user_type_tags=("ecommerce", "lead")),
    MetricSpec("meta", "instant_experience_outbound_clicks", "Instant Experience 出站点击", "engagement", "action_stats", user_type_tags=("ecommerce", "lead")),
    MetricSpec("meta", "contact_actions", "联系行为", "lead", "action_stats", user_type_tags=("lead", "finance")),
    MetricSpec("meta", "contact_value", "联系价值", "lead", "action_stats", user_type_tags=("lead", "finance")),
    MetricSpec("meta", "cost_per_contact", "联系成本", "lead", "action_stats", user_type_tags=("lead", "finance")),
    MetricSpec("meta", "submit_application_actions", "提交申请", "lead", "action_stats", user_type_tags=("finance",)),
    MetricSpec("meta", "submit_application_value", "提交申请价值", "lead", "action_stats", user_type_tags=("finance",)),
    MetricSpec("meta", "cost_per_submit_application", "提交申请成本", "lead", "action_stats", user_type_tags=("finance",)),
    MetricSpec("meta", "subscribe_actions", "订阅", "subscription", "action_stats", user_type_tags=("novel", "entertainment", "app")),
    MetricSpec("meta", "subscribe_value", "订阅价值", "subscription", "action_stats", user_type_tags=("novel", "entertainment", "app")),
    MetricSpec("meta", "cost_per_subscribe", "订阅成本", "subscription", "action_stats", user_type_tags=("novel", "entertainment", "app")),
    MetricSpec("meta", "start_trial_actions", "开始试用", "subscription", "action_stats", user_type_tags=("app", "tool", "novel")),
    MetricSpec("meta", "start_trial_value", "开始试用价值", "subscription", "action_stats", user_type_tags=("app", "tool", "novel")),
    MetricSpec("meta", "cost_per_start_trial", "开始试用成本", "subscription", "action_stats", user_type_tags=("app", "tool", "novel")),
    MetricSpec("meta", "catalog_segment_actions", "Catalog 行为", "catalog_product", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "catalog_segment_value", "Catalog 价值", "catalog_product", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "catalog_segment_value_website_purchase_roas", "Catalog 网站 ROAS", "catalog_product", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "product_views", "商品浏览", "catalog_product", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "converted_product_quantity", "转化商品数量", "catalog_product", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "converted_product_value", "转化商品价值", "catalog_product", "action_stats", user_type_tags=("ecommerce",)),
    MetricSpec("meta", "date_start", "开始日期", "attribute", "string"),
    MetricSpec("meta", "date_stop", "结束日期", "attribute", "string"),
    MetricSpec("meta", "account_id", "账户 ID", "attribute", "string"),
    MetricSpec("meta", "account_name", "账户名称", "attribute", "string"),
    MetricSpec("meta", "campaign_id", "Campaign ID", "attribute", "string", required_level="campaign"),
    MetricSpec("meta", "campaign_name", "Campaign 名称", "attribute", "string", required_level="campaign"),
    MetricSpec("meta", "objective", "推广目标", "attribute", "string", required_level="campaign"),
    MetricSpec("meta", "optimization_goal", "优化目标", "attribute", "string", required_level="adset"),
    MetricSpec("meta", "attribution_setting", "归因设置", "attribute", "string", required_level="adset"),
]

META_GROUPS: list[MetricGroup] = [
    MetricGroup("meta", "core", ("spend", "impressions", "reach", "clicks", "cpc", "cpm", "cpp", "ctr", "frequency"), "core", required_level="account"),
    MetricGroup("meta", "engagement", ("inline_link_clicks", "inline_link_click_ctr", "cost_per_inline_link_click", "outbound_clicks", "outbound_clicks_ctr", "cost_per_outbound_click", "website_clicks", "website_ctr"), "engagement", required_level="campaign"),
    MetricGroup("meta", "actions", ("actions", "action_values", "cost_per_action_type", "total_actions", "total_unique_actions", "total_action_value", "cost_per_total_action"), "conversion", required_level="campaign"),
    MetricGroup("meta", "results", ("results", "cost_per_result", "result_rate", "objective_results", "objective_result_rate", "cost_per_objective_result"), "conversion", required_level="campaign"),
    MetricGroup("meta", "value_roas", ("purchase_roas", "website_purchase_roas", "mobile_app_purchase_roas", "conversion_values", "conversions", "cost_per_conversion"), "value_roas", required_level="campaign"),
    MetricGroup("meta", "app", ("app_store_clicks", "deeplink_clicks"), "app", required_level="campaign"),
    MetricGroup("meta", "video", ("video_play_actions", "video_continuous_2_sec_watched_actions", "video_6_sec_watched_actions", "video_30_sec_watched_actions", "video_avg_time_watched_actions", "video_p25_watched_actions", "video_p50_watched_actions", "video_p75_watched_actions", "video_p95_watched_actions", "video_p100_watched_actions", "video_complete_watched_actions", "cost_per_thruplay", "cost_per_2_sec_continuous_video_view", "cost_per_15_sec_video_view"), "creative_video", required_level="ad"),
    MetricGroup("meta", "instant_experience", ("canvas_avg_view_time", "canvas_avg_view_percent", "instant_experience_clicks_to_open", "instant_experience_outbound_clicks"), "engagement", required_level="ad"),
    MetricGroup("meta", "lead", ("contact_actions", "contact_value", "cost_per_contact", "submit_application_actions", "submit_application_value", "cost_per_submit_application"), "lead", required_level="campaign"),
    MetricGroup("meta", "subscription", ("subscribe_actions", "subscribe_value", "cost_per_subscribe", "start_trial_actions", "start_trial_value", "cost_per_start_trial"), "subscription", required_level="campaign"),
    MetricGroup("meta", "catalog_product", ("catalog_segment_actions", "catalog_segment_value", "catalog_segment_value_website_purchase_roas", "product_views", "converted_product_quantity", "converted_product_value"), "catalog_product", required_level="ad"),
    MetricGroup("meta", "attributes", ("date_start", "date_stop", "account_id", "account_name", "campaign_id", "campaign_name", "objective", "optimization_goal", "attribution_setting"), "attribute", required_level="adset"),
]


TIKTOK_METRICS: list[MetricSpec] = [
    MetricSpec("tiktok", "spend", "消耗", "core", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "billed_cost", "净消耗", "core", "money", known_constraints="仅同步基础报表", user_type_tags=("all",)),
    MetricSpec("tiktok", "cash_spend", "现金消耗", "core", "money", known_constraints="广告主层级且分天查询", user_type_tags=("agency",)),
    MetricSpec("tiktok", "voucher_spend", "赠款消耗", "core", "money", known_constraints="广告主层级且分天查询", user_type_tags=("agency",)),
    MetricSpec("tiktok", "impressions", "展示", "core", user_type_tags=("all",)),
    MetricSpec("tiktok", "gross_impressions", "总展示", "core", user_type_tags=("all",)),
    MetricSpec("tiktok", "clicks", "点击", "core", user_type_tags=("all",)),
    MetricSpec("tiktok", "ctr", "CTR", "core", "rate", user_type_tags=("all",)),
    MetricSpec("tiktok", "cpc", "CPC", "core", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "cpm", "CPM", "core", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "reach", "覆盖", "core", user_type_tags=("all",)),
    MetricSpec("tiktok", "frequency", "频次", "core", user_type_tags=("all",)),
    MetricSpec("tiktok", "conversion", "转化", "conversion", user_type_tags=("all",)),
    MetricSpec("tiktok", "cost_per_conversion", "转化成本", "conversion", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "conversion_rate_v2", "CVR", "conversion", "rate", user_type_tags=("all",)),
    MetricSpec("tiktok", "real_time_conversion", "实时转化", "conversion", user_type_tags=("all",)),
    MetricSpec("tiktok", "real_time_cost_per_conversion", "实时转化成本", "conversion", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "real_time_conversion_rate_v2", "实时 CVR", "conversion", "rate", user_type_tags=("all",)),
    MetricSpec("tiktok", "result", "成效", "conversion", user_type_tags=("all",)),
    MetricSpec("tiktok", "cost_per_result", "成效成本", "conversion", "money", user_type_tags=("all",)),
    MetricSpec("tiktok", "result_rate", "成效率", "conversion", "rate", known_constraints="混合优化目标层级可能无意义", user_type_tags=("all",)),
    MetricSpec("tiktok", "secondary_goal_result", "深层目标成效", "conversion", user_type_tags=("app", "game", "finance")),
    MetricSpec("tiktok", "cost_per_secondary_goal_result", "深层目标成本", "conversion", "money", user_type_tags=("app", "game", "finance")),
    MetricSpec("tiktok", "secondary_goal_result_rate", "深层目标成效率", "conversion", "rate", user_type_tags=("app", "game", "finance")),
    MetricSpec("tiktok", "engagements", "全部点击/互动", "engagement", user_type_tags=("all",)),
    MetricSpec("tiktok", "engagement_rate", "全部点击率", "engagement", "rate", user_type_tags=("all",)),
    MetricSpec("tiktok", "likes", "点赞", "social", user_type_tags=("all",)),
    MetricSpec("tiktok", "comments", "评论", "social", user_type_tags=("all",)),
    MetricSpec("tiktok", "shares", "分享", "social", user_type_tags=("all",)),
    MetricSpec("tiktok", "follows", "关注", "social", user_type_tags=("entertainment", "social")),
    MetricSpec("tiktok", "profile_visits", "主页访问", "social", user_type_tags=("entertainment", "social")),
    MetricSpec("tiktok", "video_play_actions", "视频播放", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_watched_2s", "2 秒播放", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_watched_6s", "6 秒播放", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_views_p25", "播放 25%", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_views_p50", "播放 50%", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_views_p75", "播放 75%", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "video_views_p100", "播放完成", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "average_video_play", "平均播放时长", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "average_video_play_per_user", "用户平均播放时长", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "engaged_view", "专注观看 6 秒", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "paid_engaged_view", "付费专注观看 6 秒", "creative_video", known_constraints="需 ID 维度或 ID+stat_time_day", user_type_tags=("all",)),
    MetricSpec("tiktok", "engaged_view_15s", "专注观看 15 秒", "creative_video", user_type_tags=("all",)),
    MetricSpec("tiktok", "paid_engaged_view_15s", "付费专注观看 15 秒", "creative_video", known_constraints="需 ID 维度或 ID+stat_time_day", user_type_tags=("all",)),
    MetricSpec("tiktok", "app_install", "应用安装", "app", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "cost_per_app_install", "应用安装成本", "app", "money", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "registration", "去重注册", "app", user_type_tags=("app", "game", "finance", "social", "novel")),
    MetricSpec("tiktok", "total_registration", "注册次数", "app", user_type_tags=("app", "game", "finance", "social", "novel")),
    MetricSpec("tiktok", "purchase", "去重付费", "app", user_type_tags=("app", "game", "ecommerce")),
    MetricSpec("tiktok", "total_purchase", "付费次数", "app", user_type_tags=("app", "game", "ecommerce")),
    MetricSpec("tiktok", "total_purchase_value", "付费价值", "value_roas", "money", user_type_tags=("app", "game", "ecommerce")),
    MetricSpec("tiktok", "app_event_add_to_cart", "App 加购", "app", user_type_tags=("ecommerce", "app")),
    MetricSpec("tiktok", "checkout", "App 结账", "app", user_type_tags=("ecommerce", "app")),
    MetricSpec("tiktok", "view_content", "App 查看内容", "app", user_type_tags=("ecommerce", "app", "novel")),
    MetricSpec("tiktok", "next_day_open", "次留", "app", user_type_tags=("app", "game", "novel")),
    MetricSpec("tiktok", "day7_retention", "7 日留存", "app", user_type_tags=("app", "game", "novel")),
    MetricSpec("tiktok", "launch_app", "打开 App", "app", user_type_tags=("app", "game", "tool")),
    MetricSpec("tiktok", "complete_tutorial", "完成教程", "app", user_type_tags=("game",)),
    MetricSpec("tiktok", "create_gamerole", "创建角色", "app", user_type_tags=("game",)),
    MetricSpec("tiktok", "achieve_level", "达到等级", "app", user_type_tags=("game",)),
    MetricSpec("tiktok", "loan_apply", "申请贷款", "app", user_type_tags=("finance",)),
    MetricSpec("tiktok", "loan_credit", "批准贷款", "app", user_type_tags=("finance",)),
    MetricSpec("tiktok", "loan_disbursement", "发放贷款", "app", user_type_tags=("finance",)),
    MetricSpec("tiktok", "search", "搜索", "app", user_type_tags=("search", "novel")),
    MetricSpec("tiktok", "start_trial", "开始试用", "subscription", user_type_tags=("novel", "entertainment", "app", "tool")),
    MetricSpec("tiktok", "total_start_trial", "开始试用次数", "subscription", user_type_tags=("novel", "entertainment", "app", "tool")),
    MetricSpec("tiktok", "subscribe", "订阅", "subscription", user_type_tags=("novel", "entertainment", "app")),
    MetricSpec("tiktok", "total_subscribe_value", "订阅价值", "subscription", "money", user_type_tags=("novel", "entertainment", "app")),
    MetricSpec("tiktok", "unique_custom_app_events", "去重自定义 App 事件", "app", user_type_tags=("app", "game")),
    MetricSpec("tiktok", "custom_app_events", "自定义 App 事件", "app", user_type_tags=("app", "game")),
    MetricSpec("tiktok", "custom_app_events_value", "自定义 App 事件价值", "value_roas", "money", user_type_tags=("app", "game")),
    MetricSpec("tiktok", "complete_payment", "网页付费", "web_event", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "complete_payment_roas", "网页 ROAS", "value_roas", "rate", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "total_complete_payment_rate", "网页付费率", "web_event", "rate", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "add_to_cart", "网页加购", "web_event", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "checkout", "网页结账", "web_event", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "view_content", "网页查看内容", "web_event", user_type_tags=("ecommerce",)),
    MetricSpec("tiktok", "button_click", "按钮点击", "web_event", user_type_tags=("ecommerce", "lead")),
    MetricSpec("tiktok", "form", "表单", "web_event", user_type_tags=("lead", "finance")),
    MetricSpec("tiktok", "skan_app_install", "SKAN 安装", "skan", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "skan_cost_per_app_install", "SKAN 安装成本", "skan", "money", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "skan_registration", "SKAN 注册", "skan", user_type_tags=("app", "game", "finance")),
    MetricSpec("tiktok", "skan_purchase", "SKAN 付费", "skan", user_type_tags=("app", "game", "ecommerce")),
    MetricSpec("tiktok", "skan_total_purchase_value", "SKAN 付费价值", "skan", "money", user_type_tags=("app", "game", "ecommerce")),
    MetricSpec("tiktok", "skan_vta_app_install", "SKAN 展示归因安装", "skan", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "skan_cta_app_install", "SKAN 点击归因安装", "skan", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "real_time_app_install", "按转化时间安装", "san", user_type_tags=("app", "game", "w2a")),
    MetricSpec("tiktok", "advertiser_name", "账户名称", "attribute", "string", dimensions=("advertiser_id",)),
    MetricSpec("tiktok", "advertiser_id", "账户 ID", "attribute", "string", dimensions=("advertiser_id",)),
    MetricSpec("tiktok", "campaign_name", "推广系列名称", "attribute", "string", required_level="AUCTION_CAMPAIGN", dimensions=("campaign_id",)),
    MetricSpec("tiktok", "campaign_id", "推广系列 ID", "attribute", "string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricSpec("tiktok", "objective_type", "推广目标", "attribute", "string", required_level="AUCTION_CAMPAIGN", dimensions=("campaign_id",)),
    MetricSpec("tiktok", "campaign_automation_type", "推广系列自动化类型", "attribute", "string", required_level="AUCTION_CAMPAIGN", dimensions=("campaign_id",)),
    MetricSpec("tiktok", "adgroup_name", "广告组名称", "attribute", "string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricSpec("tiktok", "adgroup_id", "广告组 ID", "attribute", "string", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricSpec("tiktok", "promotion_type", "推广对象类型", "attribute", "string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",), user_type_tags=("w2a", "app", "web")),
    MetricSpec("tiktok", "billing_event", "计费点", "attribute", "string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricSpec("tiktok", "bid_strategy", "竞价策略", "attribute", "string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricSpec("tiktok", "ad_name", "广告名称", "attribute", "string", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricSpec("tiktok", "ad_id", "广告 ID", "attribute", "string", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricSpec("tiktok", "ad_id_v2", "广告 ID v2", "attribute", "string", required_level="AUCTION_AD", dimensions=("ad_id_v2",), known_constraints="不能和 ad_id 维度/筛选/属性同时使用；Smart+ 场景中 smart_plus_ad_id 等价于 ad_id_v2"),
    MetricSpec("tiktok", "ad_url", "广告 URL", "attribute", "string", required_level="AUCTION_AD", dimensions=("ad_id",), user_type_tags=("web", "w2a")),
    MetricSpec("tiktok", "currency", "货币", "attribute", "string", dimensions=("advertiser_id", "campaign_id", "adgroup_id", "ad_id")),
]

TIKTOK_GROUPS: list[MetricGroup] = [
    MetricGroup("tiktok", "core", ("spend", "impressions", "clicks", "ctr", "cpc", "cpm", "reach", "frequency", "conversion", "cost_per_conversion", "conversion_rate_v2", "result", "cost_per_result", "result_rate"), "core", required_level="AUCTION_ADVERTISER", dimensions=("advertiser_id",)),
    MetricGroup("tiktok", "cost_spend_detail", ("billed_cost", "cash_spend", "voucher_spend", "gross_impressions"), "core", required_level="AUCTION_ADVERTISER", dimensions=("advertiser_id",)),
    MetricGroup("tiktok", "real_time_conversion", ("real_time_conversion", "real_time_cost_per_conversion", "real_time_conversion_rate_v2", "secondary_goal_result", "cost_per_secondary_goal_result", "secondary_goal_result_rate"), "conversion", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "engagement_social", ("engagements", "engagement_rate", "likes", "comments", "shares", "follows", "profile_visits"), "social", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricGroup("tiktok", "video", ("video_play_actions", "video_watched_2s", "video_watched_6s", "video_views_p25", "video_views_p50", "video_views_p75", "video_views_p100", "average_video_play", "average_video_play_per_user", "engaged_view", "paid_engaged_view", "engaged_view_15s", "paid_engaged_view_15s"), "creative_video", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricGroup("tiktok", "app_events", ("app_install", "cost_per_app_install", "registration", "total_registration", "purchase", "total_purchase", "total_purchase_value", "app_event_add_to_cart", "checkout", "view_content", "next_day_open", "day7_retention", "launch_app", "complete_tutorial", "create_gamerole", "achieve_level", "loan_apply", "loan_credit", "loan_disbursement", "search", "start_trial", "total_start_trial", "subscribe", "total_subscribe_value", "unique_custom_app_events", "custom_app_events", "custom_app_events_value"), "app", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "web_events", ("complete_payment", "complete_payment_roas", "total_complete_payment_rate", "add_to_cart", "checkout", "view_content", "button_click", "form"), "web_event", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "skan", ("skan_app_install", "skan_cost_per_app_install", "skan_registration", "skan_purchase", "skan_total_purchase_value", "skan_vta_app_install", "skan_cta_app_install"), "skan", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "san", ("real_time_app_install",), "san", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "attributes_advertiser", ("advertiser_name", "advertiser_id", "currency"), "attribute", required_level="AUCTION_ADVERTISER", dimensions=("advertiser_id",)),
    MetricGroup("tiktok", "attributes_campaign", ("campaign_name", "objective_type", "campaign_automation_type"), "attribute", required_level="AUCTION_CAMPAIGN", dimensions=("campaign_id",)),
    MetricGroup("tiktok", "attributes_adgroup", ("campaign_id", "adgroup_name", "promotion_type", "billing_event", "bid_strategy"), "attribute", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
    MetricGroup("tiktok", "attributes_ad", ("ad_name", "ad_id", "ad_url"), "attribute", required_level="AUCTION_AD", dimensions=("ad_id",)),
    MetricGroup("tiktok", "attributes_ad_v2", ("ad_id_v2",), "attribute", required_level="AUCTION_AD", dimensions=("ad_id_v2",)),
]

TIKTOK_METRICS.extend(
    [
        *_specs(("real_time_result", "real_time_cost_per_result", "real_time_result_rate"), category="conversion", user_type_tags=("all",)),
        *_specs(("cost_per_consideration", "new_consideration_rate", "new_consideration_size"), category="social", user_type_tags=("all",)),
        *_specs(("paid_engagement_engaged_view", "paid_engagement_engaged_view_15s"), category="creative_video", user_type_tags=("all",)),
        *_specs(
            (
                "interactive_add_on_impressions",
                "interactive_add_on_destination_clicks",
                "interactive_add_on_activity_clicks",
                "interactive_add_on_option_a_clicks",
                "interactive_add_on_option_b_clicks",
                "countdown_sticker_recall_clicks",
            ),
            category="creative_video",
            user_type_tags=("all",),
        ),
        *_specs(("live_views", "live_unique_views", "live_effective_views", "live_product_clicks"), category="live", user_type_tags=("all",)),
        *_specs(("single_image_impressions", "single_image_impression_rate", "single_image_ctr"), category="creative_video", user_type_tags=("all",)),
        *_specs(
            (
                "placement_type",
                "split_test",
                "campaign_budget",
                "campaign_dedicate_type",
                "app_promotion_type",
                "opt_status",
                "adgroup_download_url",
                "profile_image",
                "dpa_target_audience_type",
                "budget",
                "smart_target",
                "bid",
                "bid_secondary_goal",
                "aeo_type",
                "tt_app_id",
                "tt_app_name",
                "mobile_app_id",
                "is_aco",
            ),
            category="attribute",
            value_type="string",
            required_level="AUCTION_ADGROUP",
            dimensions=("adgroup_id",),
            user_type_tags=("app", "game", "w2a", "web", "ecommerce"),
        ),
        *_specs(
            ("ad_text", "call_to_action", "ad_profile_image", "image_mode", "is_smart_creative"),
            category="attribute",
            value_type="string",
            required_level="AUCTION_AD",
            dimensions=("ad_id",),
            user_type_tags=("app", "game", "w2a", "web", "ecommerce"),
        ),
        *_specs(("page_browse_view", "product_details_page_browse"), category="web_event", deprecated=True, user_type_tags=("ecommerce",)),
        *_specs(("pricing_category",), category="attribute", value_type="string", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",), deprecated=True, user_type_tags=("app", "game", "w2a", "web", "ecommerce")),
        *_specs(
            (
                "website_total_find_location",
                "website_cost_per_find_location",
                "website_find_location_rate",
                "website_value_per_find_location",
                "website_total_find_location_value",
                "website_total_schedule",
                "website_cost_per_schedule",
                "website_schedule_rate",
                "website_value_per_schedule",
                "website_total_schedule_value",
                "website_total_customize_product",
                "website_cost_per_customize_product",
                "website_customize_product_rate",
                "website_value_per_customize_product",
                "website_total_customize_product_value",
            ),
            category="web_event",
            user_type_tags=("ecommerce", "lead", "finance"),
        ),
        *_specs(("onsite_destination_visits", "cost_per_onsite_destination_visit", "onsite_destination_visit_rate"), category="website", user_type_tags=("ecommerce", "w2a", "app")),
        *_specs(("onsite_ad_impression_ad_revenue_roas",), category="app", user_type_tags=("app", "game", "w2a", "novel", "entertainment", "ecommerce")),
        *_specs(
            (
                "onsite_purchases_roas",
                "onsite_total_purchase",
                "onsite_cost_per_purchase",
                "onsite_purchase_rate",
                "onsite_value_per_purchase",
                "onsite_total_purchase_value",
                "onsite_unique_purchase",
                "onsite_cost_per_unique_purchase",
                "onsite_unique_checkout_initiation",
                "onsite_cost_per_unique_checkout_initiation",
                "onsite_total_checkout_initiation",
                "onsite_cost_per_checkout_initiation",
                "onsite_checkout_initiation_rate",
                "onsite_value_per_checkout_initiation",
                "onsite_total_checkout_initiation_value",
                "onsite_total_add_to_cart",
                "onsite_cost_per_add_to_cart",
                "onsite_add_to_cart_rate",
                "onsite_value_per_add_to_cart",
                "onsite_total_add_to_cart_value",
                "onsite_unique_add_to_cart",
                "onsite_cost_per_unique_add_to_cart",
                "onsite_total_product_details_page_view",
                "onsite_cost_per_product_details_page_view",
                "onsite_product_details_page_view_rate",
                "onsite_value_per_product_details_page_view",
                "onsite_total_product_details_page_view_value",
                "onsite_total_filtered_out_form_submission",
                "onsite_unique_first_launch_conversion_time",
                "onsite_cost_per_unique_first_launch_conversion_time",
                "onsite_unique_first_launch",
                "onsite_cost_per_unique_first_launch",
                "onsite_unique_non_first_launch",
                "onsite_cost_per_unique_non_first_launch",
                "onsite_launch_rate",
                "onsite_total_non_first_launch",
                "onsite_cost_per_non_first_launch",
                "onsite_unique_registration",
                "onsite_cost_per_unique_registration",
                "onsite_registration_rate",
                "onsite_total_registration",
                "onsite_cost_per_registration",
                "onsite_unique_ad_impression",
                "onsite_cost_per_unique_ad_impression",
                "onsite_ad_impression_rate",
                "onsite_total_ad_impression",
                "onsite_cost_per_ad_impression",
                "onsite_total_ad_impression_value",
                "onsite_value_per_ad_impression",
                "onsite_add_to_wishlist",
                "cost_per_onsite_add_to_wishlist",
                "onsite_add_to_wishlist_rate",
                "value_per_onsite_add_to_wishlist",
                "total_onsite_add_to_wishlist_value",
                "onsite_add_billing",
                "cost_per_onsite_add_billing",
                "onsite_add_billing_rate",
                "value_per_onsite_add_billing",
                "total_onsite_add_billing_value",
                "onsite_form",
                "cost_per_onsite_form",
                "onsite_form_rate",
                "value_per_onsite_form",
                "total_onsite_form_value",
                "onsite_download_start",
                "cost_per_onsite_download_start",
                "onsite_download_start_rate",
                "value_per_onsite_download_start",
                "total_onsite_download_start_value",
                "onsite_unique_subscribe",
                "onsite_cost_per_unique_subscribe",
                "onsite_subscribe_rate",
                "onsite_total_subscribe",
                "onsite_cost_per_total_subscribe",
                "onsite_value_per_subscribe",
                "onsite_total_subscribe_value",
            ),
            category="app",
            user_type_tags=("app", "game", "w2a", "novel", "entertainment", "ecommerce"),
        ),
        *_specs(
            _suffix_metrics("onsite_total_purchase_value_", ("day0", "day1", "day2", "day3", "day4", "day5", "day6", "day13", "day20", "day27", "day29"))
            + _suffix_metrics("onsite_total_purchase_roas_", ("day0", "day1", "day2", "day3", "day4", "day5", "day6", "day13", "day20", "day27", "day29"))
            + _suffix_metrics("onsite_total_purchase_value_calendar_", ("day0", "day6", "day13"))
            + _suffix_metrics("onsite_total_purchase_roas_calendar_", ("day0", "day6", "day13"))
            + _suffix_metrics("onsite_ad_impression_ad_revenue_", ("day0", "day1", "day2", "day3", "day4", "day5", "day6", "day13"))
            + _suffix_metrics("onsite_ad_impression_ad_revenue_roas_", ("day0", "day1", "day2", "day3", "day4", "day5", "day6", "day13"))
            + _suffix_metrics("onsite_ad_impression_ad_revenue_calendar_", ("day0", "day6", "day13"))
            + _suffix_metrics("onsite_ad_impression_ad_revenue_roas_calendar_", ("day0", "day6", "day13"))
            + _suffix_metrics("onsite_subscribe_value_", ("day0", "day1", "day2", "day3", "day4", "day5", "day6", "day13", "day20", "day27", "day29")),
            category="app",
            user_type_tags=("app", "game", "w2a", "novel", "entertainment", "ecommerce"),
        ),
        *_specs(
            (
                "offline_total_crm_events",
                "offline_cost_per_crm_event",
                "offline_crm_event_rate",
                "offline_value_per_crm_event",
                "offline_crm_event_value",
                "offline_preferred_leads",
                "offline_cost_per_preferred_lead",
                "offline_preferred_lead_rate",
                "offline_total_find_location",
                "offline_cost_per_find_location",
                "offline_find_location_rate",
                "offline_value_per_find_location",
                "offline_total_find_location_value",
                "offline_total_schedule",
                "offline_cost_per_schedule",
                "offline_schedule_rate",
                "offline_value_per_schedule",
                "offline_total_schedule_value",
                "offline_total_customize_product",
                "offline_cost_per_customize_product",
                "offline_customize_product_rate",
                "offline_value_per_customize_product",
                "offline_total_customize_product_value",
                "offline_total_custom_events",
                "offline_cost_per_custom_event",
                "offline_custom_event_rate",
                "offline_value_per_custom_event",
                "offline_total_custom_event_value",
            ),
            category="offline",
            user_type_tags=("ecommerce", "lead", "finance", "app", "game"),
        ),
        *_specs(
            (
                "messaging_total_conversation_tiktok_direct_message",
                "messaging_cost_per_conversation_tiktok_direct_message",
                "messaging_conversation_rate_tiktok_direct_message",
                "messaging_total_conversation_instant_messaging_app",
                "messaging_cost_per_conversation_instant_messaging_app",
                "messaging_conversation_rate_instant_messaging_app",
            ),
            category="messaging",
            user_type_tags=("all",),
        ),
        *_specs(
            (
                "onsite_shopping_roas",
                "onsite_shopping",
                "cost_per_onsite_shopping",
                "onsite_shopping_rate",
                "value_per_onsite_shopping",
                "total_onsite_shopping_value",
                "shop_total_purchase_by_order_submission",
                "shop_gross_revenue_by_order_submission",
                "shop_total_items_purchased",
                "onsite_initiate_checkout_count",
                "cost_per_onsite_initiate_checkout_count",
                "onsite_initiate_checkout_count_rate",
                "value_per_onsite_initiate_checkout_count",
                "total_onsite_initiate_checkout_count_value",
                "onsite_on_web_detail",
                "cost_per_onsite_on_web_detail",
                "onsite_on_web_detail_rate",
                "value_per_onsite_on_web_detail",
                "total_onsite_on_web_detail_value",
                "onsite_on_web_cart",
                "cost_per_onsite_on_web_cart",
                "onsite_on_web_cart_rate",
                "value_per_onsite_on_web_cart",
                "total_onsite_on_web_cart_value",
            ),
            category="shop",
            user_type_tags=("ecommerce", "w2a"),
        ),
        *_specs(
            (
                "vta_conversion",
                "cost_per_vta_conversion",
                "cta_conversion",
                "cost_per_cta_conversion",
                "engaged_view_through_conversions",
                "cost_per_engaged_view_through_conversion",
                "vta_app_install",
                "cost_per_vta_app_install",
                "cta_app_install",
                "cost_per_cta_app_install",
                "evta_app_install",
                "cost_per_evta_app_install",
                "vta_registration",
                "cost_per_vta_registration",
                "cta_registration",
                "cost_per_cta_registration",
                "evta_registration",
                "cost_per_evta_registration",
                "vta_purchase",
                "cost_per_vta_purchase",
                "cta_purchase",
                "cost_per_cta_purchase",
                "evta_purchase",
                "cost_per_evta_purchase",
                "vta_complete_payment",
                "cost_per_vta_payments_completed",
                "evta_payments_completed",
                "cost_per_evta_payments_completed",
                "vta_complete_payment_value",
                "vta_complete_payment_roas",
            ),
            category="attribution",
            user_type_tags=("all",),
        ),
        *_specs(
            (
                "skan_result",
                "skan_cost_per_result",
                "skan_result_rate",
                "skan_conversion",
                "skan_cost_per_conversion",
                "skan_conversion_rate",
                "skan_conversion_rate_v2",
                "skan_click_time_conversion",
                "skan_click_time_cost_per_conversion",
                "skan_click_time_conversion_rate",
                "skan_click_time_conversion_rate_v2",
                "skan_app_install",
                "skan_cost_per_app_install",
                "skan_app_install_withheld",
                "skan_registration",
                "skan_cost_per_registration",
                "skan_registration_rate",
                "skan_total_registration",
                "skan_cost_per_total_registration",
                "skan_purchase",
                "skan_cost_per_purchase",
                "skan_purchase_rate",
                "skan_total_purchase",
                "skan_cost_per_total_purchase",
                "skan_total_purchase_value",
                "skan_total_repetitive_active_pay_roas",
                "skan_add_to_cart",
                "skan_cost_per_add_to_cart",
                "skan_add_to_cart_rate",
                "skan_total_add_to_cart",
                "skan_cost_per_total_add_to_cart",
                "skan_total_add_to_cart_value",
                "skan_checkout",
                "skan_cost_per_checkout",
                "skan_checkout_rate",
                "skan_total_checkout",
                "skan_cost_per_total_checkout",
                "skan_total_checkout_value",
                "skan_view_content",
                "skan_cost_per_view_content",
                "skan_view_content_rate",
                "skan_total_view_content",
                "skan_cost_per_total_view_content",
                "skan_total_view_content_value",
                "skan_add_payment_info",
                "skan_cost_per_add_payment_info",
                "skan_add_payment_info_rate",
                "skan_total_add_payment_info",
                "skan_cost_total_add_payment_info",
                "skan_add_to_wishlist",
                "skan_cost_per_add_to_wishlist",
                "skan_add_to_wishlist_rate",
                "skan_total_add_to_wishlist",
                "skan_cost_per_total_add_to_wishlist",
                "skan_total_add_to_wishlist_value",
                "skan_launch_app",
                "skan_cost_per_launch_app",
                "skan_launch_app_rate",
                "skan_total_launch_app",
                "skan_cost_per_total_launch_app",
                "skan_complete_tutorial",
                "skan_cost_per_complete_tutorial",
                "skan_complete_tutorial_rate",
                "skan_total_complete_tutorial",
                "skan_cost_per_total_complete_tutorial",
                "skan_total_complete_tutorial_value",
                "skan_create_group",
                "skan_cost_per_create_group",
                "skan_create_group_rate",
                "skan_total_create_group",
                "skan_cost_per_total_create_group",
                "skan_total_create_group_value",
                "skan_join_group",
                "skan_cost_per_join_group",
                "skan_join_group_rate",
                "skan_total_join_group",
                "skan_cost_per_total_join_group",
                "skan_total_join_group_value",
                "skan_create_gamerole",
                "skan_cost_per_create_gamerole",
                "skan_create_gamerole_rate",
                "skan_total_create_gamerole",
                "skan_cost_per_total_create_gamerole",
                "skan_total_create_gamerole_value",
                "skan_spend_credits",
                "skan_cost_per_spend_credits",
                "skan_spend_credits_rate",
                "skan_total_spend_credits",
                "skan_cost_per_total_spend_credits",
                "skan_total_spend_credits_value",
                "skan_achieve_level",
                "skan_cost_per_achieve_level",
                "skan_achieve_level_rate",
                "skan_total_achieve_level",
                "skan_cost_per_total_achieve_level",
                "skan_total_achieve_level_value",
                "skan_unlock_achievement",
                "skan_cost_per_unlock_achievement",
                "skan_unlock_achievement_rate",
                "skan_total_unlock_achievement",
                "skan_cost_per_total_unlock_achievement",
                "skan_total_unlock_achievement_value",
                "skan_sales_lead",
                "skan_cost_per_sales_lead",
                "skan_sales_lead_rate",
                "skan_total_sales_lead",
                "skan_cost_per_total_sales_lead",
                "skan_total_sales_lead_value",
                "skan_in_app_ad_click",
                "skan_cost_per_in_app_ad_click",
                "skan_in_app_ad_click_rate",
                "skan_total_in_app_ad_click",
                "skan_cost_per_total_in_app_ad_click",
                "skan_total_in_app_ad_click_value",
                "skan_in_app_ad_impr",
                "skan_cost_per_in_app_ad_impr",
                "skan_in_app_ad_impr_rate",
                "skan_total_in_app_ad_impr",
                "skan_cost_per_total_in_app_ad_impr",
                "skan_total_in_app_ad_impr_value",
                "skan_loan_apply",
                "skan_cost_per_loan_apply",
                "skan_loan_apply_rate",
                "skan_total_loan_apply",
                "skan_cost_per_total_loan_apply",
                "skan_loan_credit",
                "skan_cost_per_loan_credit",
                "skan_loan_credit_rate",
                "skan_total_loan_credit",
                "skan_cost_per_total_loan_credit",
                "skan_loan_disbursement",
                "skan_cost_per_loan_disbursement",
                "skan_loan_disbursement_rate",
                "skan_total_loan_disbursement",
                "skan_cost_per_total_loan_disbursement",
                "skan_login",
                "skan_cost_per_login",
                "skan_login_rate",
                "skan_total_login",
                "skan_cost_per_total_login",
                "skan_ratings",
                "skan_cost_per_ratings",
                "skan_ratings_rate",
                "skan_total_ratings",
                "skan_cost_per_total_ratings",
                "skan_total_ratings_value",
                "skan_search",
                "skan_cost_per_search",
                "skan_search_rate",
                "skan_total_search",
                "skan_cost_per_total_search",
                "skan_start_trial",
                "skan_cost_per_start_trial",
                "skan_start_trial_rate",
                "skan_total_start_trial",
                "skan_cost_per_total_start_trial",
                "skan_subscribe",
                "skan_cost_per_subscribe",
                "skan_subscribe_rate",
                "skan_total_subscribe",
                "skan_cost_per_total_subscribe",
                "skan_total_subscribe_value",
                "skan_vta_conversion",
                "skan_cost_per_vta_conversion",
                "skan_vta_app_install",
                "skan_cost_per_vta_app_install",
                "skan_vta_registration",
                "skan_cost_per_vta_registration",
                "skan_vta_purchase",
                "skan_cost_per_vta_purchase",
                "skan_cta_conversion",
                "skan_cost_per_cta_conversion",
                "skan_cta_app_install",
                "skan_cost_per_cta_app_install",
                "skan_cta_registration",
                "skan_cost_per_cta_registration",
                "skan_cta_purchase",
                "skan_cost_per_cta_purchase",
            ),
            category="skan",
            user_type_tags=("app", "game", "ecommerce", "w2a", "finance", "novel", "entertainment"),
        ),
        *_specs(("real_time_app_install", "registration", "total_registration", "purchase", "total_purchase", "total_purchase_value", "app_event_add_to_cart", "total_app_event_add_to_cart", "total_app_event_add_to_cart_value", "checkout", "total_checkout", "total_checkout_value", "view_content", "total_view_content", "total_view_content_value", "next_day_open", "total_next_day_open", "day7_retention", "total_day7_retention", "total_day7_retention_value", "launch_app", "total_launch_app", "complete_tutorial", "total_complete_tutorial", "total_complete_tutorial_value", "create_group", "total_create_group", "total_create_group_value", "join_group", "total_join_group", "total_join_group_value", "create_gamerole", "total_create_gamerole", "total_create_gamerole_value", "spend_credits", "total_spend_credits", "total_spend_credits_value", "achieve_level", "total_achieve_level", "total_achieve_level_value", "unlock_achievement", "total_unlock_achievement", "total_unlock_achievement_value", "sales_lead", "total_sales_lead", "total_sales_lead_value", "in_app_ad_click", "total_in_app_ad_click", "total_in_app_ad_click_value", "in_app_ad_impr", "total_in_app_ad_impr", "total_in_app_ad_impr_value", "loan_apply", "total_loan_apply", "loan_credit", "total_loan_credit", "loan_disbursement", "total_loan_disbursement", "login", "total_login", "ratings", "total_ratings", "total_ratings_value", "search", "total_search", "start_trial", "total_start_trial", "subscribe", "total_subscribe", "total_subscribe_value", "unique_custom_app_events", "custom_app_events", "custom_app_events_value", "unique_ad_impression_events", "ads_impression_events", "total_ad_impression_events_value"), category="san", user_type_tags=("app", "game", "w2a", "novel", "entertainment", "finance")),
    ]
)

TIKTOK_GROUPS.extend(
    [
        MetricGroup("tiktok", "creative_interactive", ("interactive_add_on_impressions", "interactive_add_on_destination_clicks", "interactive_add_on_activity_clicks", "interactive_add_on_option_a_clicks", "interactive_add_on_option_b_clicks", "countdown_sticker_recall_clicks"), "creative_video", required_level="AUCTION_AD", dimensions=("ad_id",)),
        MetricGroup("tiktok", "live", ("live_views", "live_unique_views", "live_effective_views", "live_product_clicks"), "live", required_level="AUCTION_AD", dimensions=("ad_id",)),
        MetricGroup("tiktok", "social_consideration", ("cost_per_consideration", "new_consideration_rate", "new_consideration_size"), "social", required_level="AUCTION_AD", dimensions=("ad_id",)),
        MetricGroup("tiktok", "website_extra", ("website_total_find_location", "website_cost_per_find_location", "website_find_location_rate", "website_value_per_find_location", "website_total_find_location_value", "website_total_schedule", "website_cost_per_schedule", "website_schedule_rate", "website_value_per_schedule", "website_total_schedule_value", "website_total_customize_product", "website_cost_per_customize_product", "website_customize_product_rate", "website_value_per_customize_product", "website_total_customize_product_value"), "web_event", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "onsite_app", ("onsite_purchases_roas", "onsite_total_purchase", "onsite_cost_per_purchase", "onsite_purchase_rate", "onsite_value_per_purchase", "onsite_total_purchase_value", "onsite_unique_purchase", "onsite_cost_per_unique_purchase", "onsite_unique_checkout_initiation", "onsite_cost_per_unique_checkout_initiation", "onsite_total_checkout_initiation", "onsite_cost_per_checkout_initiation", "onsite_checkout_initiation_rate", "onsite_value_per_checkout_initiation", "onsite_total_checkout_initiation_value", "onsite_total_add_to_cart", "onsite_cost_per_add_to_cart", "onsite_add_to_cart_rate", "onsite_value_per_add_to_cart", "onsite_total_add_to_cart_value", "onsite_unique_add_to_cart", "onsite_cost_per_unique_add_to_cart", "onsite_total_product_details_page_view", "onsite_cost_per_product_details_page_view", "onsite_product_details_page_view_rate", "onsite_value_per_product_details_page_view", "onsite_total_product_details_page_view_value", "onsite_total_filtered_out_form_submission", "onsite_unique_first_launch_conversion_time", "onsite_cost_per_unique_first_launch_conversion_time", "onsite_unique_first_launch", "onsite_cost_per_unique_first_launch", "onsite_unique_non_first_launch", "onsite_cost_per_unique_non_first_launch", "onsite_launch_rate", "onsite_total_non_first_launch", "onsite_cost_per_non_first_launch", "onsite_unique_registration", "onsite_cost_per_unique_registration", "onsite_registration_rate", "onsite_total_registration", "onsite_cost_per_registration", "onsite_unique_ad_impression", "onsite_cost_per_unique_ad_impression", "onsite_ad_impression_rate", "onsite_total_ad_impression", "onsite_cost_per_ad_impression", "onsite_total_ad_impression_value", "onsite_value_per_ad_impression", "onsite_add_to_wishlist", "cost_per_onsite_add_to_wishlist", "onsite_add_to_wishlist_rate", "value_per_onsite_add_to_wishlist", "total_onsite_add_to_wishlist_value", "onsite_add_billing", "cost_per_onsite_add_billing", "onsite_add_billing_rate", "value_per_onsite_add_billing", "total_onsite_add_billing_value", "onsite_form", "cost_per_onsite_form", "onsite_form_rate", "value_per_onsite_form", "total_onsite_form_value", "onsite_download_start", "cost_per_onsite_download_start", "onsite_download_start_rate", "value_per_onsite_download_start", "total_onsite_download_start_value", "onsite_unique_subscribe", "onsite_cost_per_unique_subscribe", "onsite_subscribe_rate", "onsite_total_subscribe", "onsite_cost_per_total_subscribe", "onsite_value_per_subscribe", "onsite_total_subscribe_value"), "app", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "onsite_revenue_buckets", ("onsite_total_purchase_value_day0", "onsite_total_purchase_value_day1", "onsite_total_purchase_value_day2", "onsite_total_purchase_value_day3", "onsite_total_purchase_value_day4", "onsite_total_purchase_value_day5", "onsite_total_purchase_value_day6", "onsite_total_purchase_value_day13", "onsite_total_purchase_value_day20", "onsite_total_purchase_value_day27", "onsite_total_purchase_value_day29", "onsite_total_purchase_roas_day0", "onsite_total_purchase_roas_day1", "onsite_total_purchase_roas_day2", "onsite_total_purchase_roas_day3", "onsite_total_purchase_roas_day4", "onsite_total_purchase_roas_day5", "onsite_total_purchase_roas_day6", "onsite_total_purchase_roas_day13", "onsite_total_purchase_roas_day20", "onsite_total_purchase_roas_day27", "onsite_total_purchase_roas_day29", "onsite_total_purchase_value_calendar_day0", "onsite_total_purchase_value_calendar_day6", "onsite_total_purchase_value_calendar_day13", "onsite_total_purchase_roas_calendar_day0", "onsite_total_purchase_roas_calendar_day6", "onsite_total_purchase_roas_calendar_day13", "onsite_ad_impression_ad_revenue_day0", "onsite_ad_impression_ad_revenue_day1", "onsite_ad_impression_ad_revenue_day2", "onsite_ad_impression_ad_revenue_day3", "onsite_ad_impression_ad_revenue_day4", "onsite_ad_impression_ad_revenue_day5", "onsite_ad_impression_ad_revenue_day6", "onsite_ad_impression_ad_revenue_day13", "onsite_ad_impression_ad_revenue_roas", "onsite_ad_impression_ad_revenue_roas_day0", "onsite_ad_impression_ad_revenue_roas_day1", "onsite_ad_impression_ad_revenue_roas_day2", "onsite_ad_impression_ad_revenue_roas_day3", "onsite_ad_impression_ad_revenue_roas_day4", "onsite_ad_impression_ad_revenue_roas_day5", "onsite_ad_impression_ad_revenue_roas_day6", "onsite_ad_impression_ad_revenue_roas_day13", "onsite_ad_impression_ad_revenue_calendar_day0", "onsite_ad_impression_ad_revenue_calendar_day6", "onsite_ad_impression_ad_revenue_calendar_day13", "onsite_ad_impression_ad_revenue_roas_calendar_day0", "onsite_ad_impression_ad_revenue_roas_calendar_day6", "onsite_ad_impression_ad_revenue_roas_calendar_day13", "onsite_subscribe_value_day0", "onsite_subscribe_value_day1", "onsite_subscribe_value_day2", "onsite_subscribe_value_day3", "onsite_subscribe_value_day4", "onsite_subscribe_value_day5", "onsite_subscribe_value_day6", "onsite_subscribe_value_day13", "onsite_subscribe_value_day20", "onsite_subscribe_value_day27", "onsite_subscribe_value_day29"), "app", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "offline", ("offline_total_crm_events", "offline_cost_per_crm_event", "offline_crm_event_rate", "offline_value_per_crm_event", "offline_crm_event_value", "offline_preferred_leads", "offline_cost_per_preferred_lead", "offline_preferred_lead_rate", "offline_total_find_location", "offline_cost_per_find_location", "offline_find_location_rate", "offline_value_per_find_location", "offline_total_find_location_value", "offline_total_schedule", "offline_cost_per_schedule", "offline_schedule_rate", "offline_value_per_schedule", "offline_total_schedule_value", "offline_total_customize_product", "offline_cost_per_customize_product", "offline_customize_product_rate", "offline_value_per_customize_product", "offline_total_customize_product_value", "offline_total_custom_events", "offline_cost_per_custom_event", "offline_custom_event_rate", "offline_value_per_custom_event", "offline_total_custom_event_value"), "offline", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "messaging", ("messaging_total_conversation_tiktok_direct_message", "messaging_cost_per_conversation_tiktok_direct_message", "messaging_conversation_rate_tiktok_direct_message", "messaging_total_conversation_instant_messaging_app", "messaging_cost_per_conversation_instant_messaging_app", "messaging_conversation_rate_instant_messaging_app"), "messaging", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "shop", ("onsite_shopping_roas", "onsite_shopping", "cost_per_onsite_shopping", "onsite_shopping_rate", "value_per_onsite_shopping", "total_onsite_shopping_value", "shop_total_purchase_by_order_submission", "shop_gross_revenue_by_order_submission", "shop_total_items_purchased", "onsite_initiate_checkout_count", "cost_per_onsite_initiate_checkout_count", "onsite_initiate_checkout_count_rate", "value_per_onsite_initiate_checkout_count", "total_onsite_initiate_checkout_count_value", "onsite_on_web_detail", "cost_per_onsite_on_web_detail", "onsite_on_web_detail_rate", "value_per_onsite_on_web_detail", "total_onsite_on_web_detail_value", "onsite_on_web_cart", "cost_per_onsite_on_web_cart", "onsite_on_web_cart_rate", "value_per_onsite_on_web_cart", "total_onsite_on_web_cart_value"), "shop", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "attribution", ("vta_conversion", "cost_per_vta_conversion", "cta_conversion", "cost_per_cta_conversion", "engaged_view_through_conversions", "cost_per_engaged_view_through_conversion", "vta_app_install", "cost_per_vta_app_install", "cta_app_install", "cost_per_cta_app_install", "evta_app_install", "cost_per_evta_app_install", "vta_registration", "cost_per_vta_registration", "cta_registration", "cost_per_cta_registration", "evta_registration", "cost_per_evta_registration", "vta_purchase", "cost_per_vta_purchase", "cta_purchase", "cost_per_cta_purchase", "evta_purchase", "cost_per_evta_purchase", "vta_complete_payment", "cost_per_vta_payments_completed", "evta_payments_completed", "cost_per_evta_payments_completed", "vta_complete_payment_value", "vta_complete_payment_roas"), "attribution", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "skan_full", ("skan_result", "skan_cost_per_result", "skan_result_rate", "skan_conversion", "skan_cost_per_conversion", "skan_conversion_rate", "skan_conversion_rate_v2", "skan_click_time_conversion", "skan_click_time_cost_per_conversion", "skan_click_time_conversion_rate", "skan_click_time_conversion_rate_v2", "skan_app_install", "skan_cost_per_app_install", "skan_app_install_withheld", "skan_registration", "skan_cost_per_registration", "skan_registration_rate", "skan_total_registration", "skan_cost_per_total_registration", "skan_purchase", "skan_cost_per_purchase", "skan_purchase_rate", "skan_total_purchase", "skan_cost_per_total_purchase", "skan_total_purchase_value", "skan_total_repetitive_active_pay_roas", "skan_add_to_cart", "skan_cost_per_add_to_cart", "skan_add_to_cart_rate", "skan_total_add_to_cart", "skan_cost_per_total_add_to_cart", "skan_total_add_to_cart_value", "skan_checkout", "skan_cost_per_checkout", "skan_checkout_rate", "skan_total_checkout", "skan_cost_per_total_checkout", "skan_total_checkout_value", "skan_view_content", "skan_cost_per_view_content", "skan_view_content_rate", "skan_total_view_content", "skan_cost_per_total_view_content", "skan_total_view_content_value", "skan_add_payment_info", "skan_cost_per_add_payment_info", "skan_add_payment_info_rate", "skan_total_add_payment_info", "skan_cost_total_add_payment_info", "skan_add_to_wishlist", "skan_cost_per_add_to_wishlist", "skan_add_to_wishlist_rate", "skan_total_add_to_wishlist", "skan_cost_per_total_add_to_wishlist", "skan_total_add_to_wishlist_value", "skan_launch_app", "skan_cost_per_launch_app", "skan_launch_app_rate", "skan_total_launch_app", "skan_cost_per_total_launch_app", "skan_complete_tutorial", "skan_cost_per_complete_tutorial", "skan_complete_tutorial_rate", "skan_total_complete_tutorial", "skan_cost_per_total_complete_tutorial", "skan_total_complete_tutorial_value", "skan_create_group", "skan_cost_per_create_group", "skan_create_group_rate", "skan_total_create_group", "skan_cost_per_total_create_group", "skan_total_create_group_value", "skan_join_group", "skan_cost_per_join_group", "skan_join_group_rate", "skan_total_join_group", "skan_cost_per_total_join_group", "skan_total_join_group_value", "skan_create_gamerole", "skan_cost_per_create_gamerole", "skan_create_gamerole_rate", "skan_total_create_gamerole", "skan_cost_per_total_create_gamerole", "skan_total_create_gamerole_value", "skan_spend_credits", "skan_cost_per_spend_credits", "skan_spend_credits_rate", "skan_total_spend_credits", "skan_cost_per_total_spend_credits", "skan_total_spend_credits_value", "skan_achieve_level", "skan_cost_per_achieve_level", "skan_achieve_level_rate", "skan_total_achieve_level", "skan_cost_per_total_achieve_level", "skan_total_achieve_level_value", "skan_unlock_achievement", "skan_cost_per_unlock_achievement", "skan_unlock_achievement_rate", "skan_total_unlock_achievement", "skan_cost_per_total_unlock_achievement", "skan_total_unlock_achievement_value", "skan_sales_lead", "skan_cost_per_sales_lead", "skan_sales_lead_rate", "skan_total_sales_lead", "skan_cost_per_total_sales_lead", "skan_total_sales_lead_value", "skan_in_app_ad_click", "skan_cost_per_in_app_ad_click", "skan_in_app_ad_click_rate", "skan_total_in_app_ad_click", "skan_cost_per_total_in_app_ad_click", "skan_total_in_app_ad_click_value", "skan_in_app_ad_impr", "skan_cost_per_in_app_ad_impr", "skan_in_app_ad_impr_rate", "skan_total_in_app_ad_impr", "skan_cost_per_total_in_app_ad_impr", "skan_total_in_app_ad_impr_value", "skan_loan_apply", "skan_cost_per_loan_apply", "skan_loan_apply_rate", "skan_total_loan_apply", "skan_cost_per_total_loan_apply", "skan_loan_credit", "skan_cost_per_loan_credit", "skan_loan_credit_rate", "skan_total_loan_credit", "skan_cost_per_total_loan_credit", "skan_loan_disbursement", "skan_cost_per_loan_disbursement", "skan_loan_disbursement_rate", "skan_total_loan_disbursement", "skan_cost_per_total_loan_disbursement", "skan_login", "skan_cost_per_login", "skan_login_rate", "skan_total_login", "skan_cost_per_total_login", "skan_ratings", "skan_cost_per_ratings", "skan_ratings_rate", "skan_total_ratings", "skan_cost_per_total_ratings", "skan_total_ratings_value", "skan_search", "skan_cost_per_search", "skan_search_rate", "skan_total_search", "skan_cost_per_total_search", "skan_start_trial", "skan_cost_per_start_trial", "skan_start_trial_rate", "skan_total_start_trial", "skan_cost_per_total_start_trial", "skan_subscribe", "skan_cost_per_subscribe", "skan_subscribe_rate", "skan_total_subscribe", "skan_cost_per_total_subscribe", "skan_total_subscribe_value", "skan_vta_conversion", "skan_cost_per_vta_conversion", "skan_vta_app_install", "skan_cost_per_vta_app_install", "skan_vta_registration", "skan_cost_per_vta_registration", "skan_vta_purchase", "skan_cost_per_vta_purchase", "skan_cta_conversion", "skan_cost_per_cta_conversion", "skan_cta_app_install", "skan_cost_per_cta_app_install", "skan_cta_registration", "skan_cost_per_cta_registration", "skan_cta_purchase", "skan_cost_per_cta_purchase"), "skan", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "attributes_campaign_extra", ("split_test", "campaign_budget", "campaign_dedicate_type", "app_promotion_type"), "attribute", required_level="AUCTION_CAMPAIGN", dimensions=("campaign_id",)),
        MetricGroup("tiktok", "attributes_adgroup_extra", ("placement_type", "opt_status", "adgroup_download_url", "profile_image", "dpa_target_audience_type", "budget", "smart_target", "bid", "bid_secondary_goal", "aeo_type", "tt_app_id", "tt_app_name", "mobile_app_id", "is_aco"), "attribute", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "attributes_adgroup_deprecated", ("pricing_category",), "attribute", required_level="AUCTION_ADGROUP", dimensions=("adgroup_id",)),
        MetricGroup("tiktok", "attributes_ad_extra", ("ad_text", "call_to_action", "ad_profile_image", "image_mode", "is_smart_creative"), "attribute", required_level="AUCTION_AD", dimensions=("ad_id",)),
    ]
)


META_METRIC_MAP = metric_map(META_METRICS)
TIKTOK_METRIC_MAP = metric_map(TIKTOK_METRICS)
