from __future__ import annotations

import argparse

from motata_cli.meta import commands


def add_common_auth_arguments(parser: argparse.ArgumentParser, *, needs_account: bool = True) -> None:
    if needs_account:
        parser.add_argument("--account-id", "--account", dest="account_id", required=True)
    else:
        parser.add_argument("--account-id", "--account", dest="account_id")
    parser.add_argument("--access-token", default=commands.env_first("META_ACCESS_TOKEN", "MOTATA_META_ACCESS_TOKEN"))
    parser.add_argument("--json", action="store_true", default=True)


def add_payload_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--payload-json")
    parser.add_argument("--payload-file")


def register_meta_commands(subparsers) -> None:
    meta = subparsers.add_parser("meta", help="Meta/Facebook advertising operations")
    meta.add_argument("--output", choices=["json", "plain", "table"], help="Override output format for Meta commands.")
    meta.add_argument("--debug", action="store_true", help="Print raw Meta request details to stderr.")
    meta_subparsers = meta.add_subparsers(dest="meta_command", required=True)

    accounts = meta_subparsers.add_parser("accounts", aliases=["adaccount", "adaccounts"])
    accounts_sub = accounts.add_subparsers(dest="accounts_command", required=True)
    p = accounts_sub.add_parser("list")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_accounts_list)

    p = accounts_sub.add_parser("info")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("account_ref")
    p.set_defaults(func=commands.command_accounts_info)

    p = accounts_sub.add_parser("inspect")
    add_common_auth_arguments(p)
    p.set_defaults(func=commands.command_accounts_inspect)

    assets = meta_subparsers.add_parser("assets")
    assets_sub = assets.add_subparsers(dest="assets_command", required=True)
    for name, func in [
        ("discover", commands.command_assets_discover),
        ("pages", commands.command_assets_pages),
        ("promotable-pages", commands.command_assets_promotable_pages),
        ("pixels", commands.command_assets_pixels),
        ("instagram", commands.command_assets_instagram),
    ]:
        p = assets_sub.add_parser(name)
        add_common_auth_arguments(p)
        if name == "pages":
            p.add_argument("--fields", nargs="*")
            p.add_argument("--limit", type=int, default=25)
            p.add_argument("--after")
            p.add_argument("--all", action="store_true")
        p.set_defaults(func=func)

    media = meta_subparsers.add_parser("media")
    media_sub = media.add_subparsers(dest="media_command", required=True)
    p = media_sub.add_parser("upload-image")
    add_common_auth_arguments(p)
    p.add_argument("--file", required=True)
    p.add_argument("--name")
    p.set_defaults(func=commands.command_media_upload_image)

    p = media_sub.add_parser("upload-video")
    add_common_auth_arguments(p)
    p.add_argument("--file", required=True)
    p.add_argument("--title")
    p.add_argument("--name")
    p.add_argument("--thumbnail")
    p.add_argument("--auto-thumbnail", action="store_true")
    p.set_defaults(func=commands.command_media_upload_video)

    images = meta_subparsers.add_parser("images")
    images_sub = images.add_subparsers(dest="images_command", required=True)
    p = images_sub.add_parser("upload")
    add_common_auth_arguments(p)
    p.add_argument("--file", required=True)
    p.add_argument("--name")
    p.set_defaults(func=commands.command_media_upload_image)

    videos = meta_subparsers.add_parser("videos")
    videos_sub = videos.add_subparsers(dest="videos_command", required=True)
    p = videos_sub.add_parser("upload")
    add_common_auth_arguments(p)
    p.add_argument("--file", required=True)
    p.add_argument("--title")
    p.add_argument("--name")
    p.add_argument("--thumbnail")
    p.add_argument("--auto-thumbnail", action="store_true")
    p.set_defaults(func=commands.command_media_upload_video)

    creatives = meta_subparsers.add_parser("creatives", aliases=["creative"])
    creatives_sub = creatives.add_subparsers(dest="creatives_command", required=True)
    p = creatives_sub.add_parser("list")
    add_common_auth_arguments(p)
    p.add_argument("--ad")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_creatives_list)

    p = creatives_sub.add_parser("get")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("creative_id")
    p.add_argument("--fields", nargs="*")
    p.set_defaults(func=commands.command_creatives_get)

    p = creatives_sub.add_parser("create")
    add_common_auth_arguments(p)
    p.add_argument("--name", required=True)
    p.add_argument("--page-id")
    p.add_argument("--instagram-user-id")
    p.add_argument("--instagram-actor-id", dest="instagram_actor_id")
    p.add_argument("--video-id")
    p.add_argument("--image-hash")
    p.add_argument("--link")
    p.add_argument("--message")
    p.add_argument("--headline")
    p.add_argument("--description")
    p.add_argument("--call-to-action", default="SHOP_NOW")
    p.add_argument("--object-story-spec")
    p.add_argument("--asset-feed-spec")
    p.add_argument("--media-sourcing-spec")
    p.add_argument("--url-tags")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_creatives_create)

    p = creatives_sub.add_parser("update")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("creative_id")
    p.add_argument("--name")
    p.add_argument("--page-id")
    p.add_argument("--instagram-user-id")
    p.add_argument("--instagram-actor-id", dest="instagram_actor_id")
    p.add_argument("--video-id")
    p.add_argument("--image-hash")
    p.add_argument("--link")
    p.add_argument("--message")
    p.add_argument("--headline")
    p.add_argument("--description")
    p.add_argument("--call-to-action")
    p.add_argument("--object-story-id")
    p.add_argument("--object-story-spec")
    p.add_argument("--asset-feed-spec")
    p.add_argument("--media-sourcing-spec")
    p.add_argument("--url-tags")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_creatives_update)

    campaigns = meta_subparsers.add_parser("campaigns", aliases=["campaign"])
    campaigns_sub = campaigns.add_subparsers(dest="campaigns_command", required=True)
    p = campaigns_sub.add_parser("list")
    add_common_auth_arguments(p)
    p.add_argument("--status", nargs="*")
    p.add_argument("--objective")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_campaigns_list)

    p = campaigns_sub.add_parser("get")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("campaign_id")
    p.add_argument("--fields", nargs="*")
    p.set_defaults(func=commands.command_campaigns_get)

    p = campaigns_sub.add_parser("create")
    add_common_auth_arguments(p)
    p.add_argument("--name", required=True)
    p.add_argument("--objective", required=True)
    p.add_argument("--status", default="PAUSED")
    p.add_argument("--daily-budget")
    p.add_argument("--lifetime-budget")
    p.add_argument("--bid-strategy")
    p.add_argument("--bid-cap")
    p.add_argument("--bid-constraints", dest="bid_constraints_json")
    p.add_argument("--special-ad-categories", nargs="*")
    p.add_argument("--use-adset-level-budgets", action="store_true")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_campaigns_create)

    p = campaigns_sub.add_parser("update")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("campaign_id")
    p.add_argument("--name")
    p.add_argument("--status")
    p.add_argument("--daily-budget")
    p.add_argument("--lifetime-budget")
    p.add_argument("--bid-strategy")
    p.add_argument("--bid-cap")
    p.add_argument("--bid-constraints", dest="bid_constraints_json")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_campaigns_update)

    adsets = meta_subparsers.add_parser("adsets", aliases=["adset"])
    adsets_sub = adsets.add_subparsers(dest="adsets_command", required=True)
    p = adsets_sub.add_parser("list")
    add_common_auth_arguments(p)
    p.add_argument("--campaign")
    p.add_argument("--status", nargs="*")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_adsets_list)

    p = adsets_sub.add_parser("get")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("adset_id")
    p.add_argument("--fields", nargs="*")
    p.set_defaults(func=commands.command_adsets_get)

    p = adsets_sub.add_parser("create")
    add_common_auth_arguments(p)
    p.add_argument("--campaign-id", required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--optimization-goal", required=True)
    p.add_argument("--billing-event", required=True)
    p.add_argument("--status", default="PAUSED")
    p.add_argument("--targeting", "--targeting-json", dest="targeting_json", required=True)
    p.add_argument("--daily-budget")
    p.add_argument("--lifetime-budget")
    p.add_argument("--bid-amount")
    p.add_argument("--bid-strategy")
    p.add_argument("--bid-constraints", dest="bid_constraints_json")
    p.add_argument("--start-time")
    p.add_argument("--end-time")
    p.add_argument("--destination-type")
    p.add_argument("--promoted-object", "--promoted-object-json", dest="promoted_object_json")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_adsets_create)

    p = adsets_sub.add_parser("update")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("adset_id")
    p.add_argument("--name")
    p.add_argument("--status")
    p.add_argument("--daily-budget")
    p.add_argument("--lifetime-budget")
    p.add_argument("--bid-amount")
    p.add_argument("--bid-strategy")
    p.add_argument("--bid-constraints", dest="bid_constraints_json")
    p.add_argument("--targeting", "--targeting-json", dest="targeting_json")
    p.add_argument("--start-time")
    p.add_argument("--end-time")
    p.add_argument("--frequency-cap", dest="frequency_cap_json")
    p.add_argument("--frequency-control-specs", dest="frequency_control_specs_json")
    p.add_argument("--destination-type")
    p.add_argument("--promoted-object", "--promoted-object-json", dest="promoted_object_json")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_adsets_update)

    ads = meta_subparsers.add_parser("ads", aliases=["ad"])
    ads_sub = ads.add_subparsers(dest="ads_command", required=True)
    p = ads_sub.add_parser("list")
    add_common_auth_arguments(p)
    p.add_argument("--adset")
    p.add_argument("--campaign")
    p.add_argument("--status", nargs="*")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_ads_list)

    p = ads_sub.add_parser("get")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("ad_id")
    p.add_argument("--fields", nargs="*")
    p.set_defaults(func=commands.command_ads_get)

    p = ads_sub.add_parser("create")
    add_common_auth_arguments(p)
    p.add_argument("--name", required=True)
    p.add_argument("--adset-id", required=True)
    p.add_argument("--creative-id")
    p.add_argument("--status", default="PAUSED")
    p.add_argument("--bid-amount")
    p.add_argument("--tracking-specs", dest="tracking_specs_json")
    p.add_argument("--conversion-domain")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_ads_create)

    p = ads_sub.add_parser("update")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("ad_id")
    p.add_argument("--name")
    p.add_argument("--status")
    p.add_argument("--creative-id")
    p.add_argument("--bid-amount")
    p.add_argument("--tracking-specs", dest="tracking_specs_json")
    p.add_argument("--conversion-domain")
    add_payload_arguments(p)
    p.set_defaults(func=commands.command_ads_update)

    pages = meta_subparsers.add_parser("pages", aliases=["page"])
    pages_sub = pages.add_subparsers(dest="pages_command", required=True)
    p = pages_sub.add_parser("list")
    add_common_auth_arguments(p)
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.add_argument("--after")
    p.add_argument("--all", action="store_true")
    p.set_defaults(func=commands.command_pages_list)

    p = pages_sub.add_parser("instagram")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("page_id")
    p.set_defaults(func=commands.command_pages_instagram)

    insights = meta_subparsers.add_parser("insights")
    insights_sub = insights.add_subparsers(dest="insights_command", required=True)
    p = insights_sub.add_parser("get")
    add_common_auth_arguments(p)
    p.add_argument("--campaign")
    p.add_argument("--adset")
    p.add_argument("--ad")
    p.add_argument("--level")
    p.add_argument("--date-preset")
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--breakdowns", nargs="*")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--time-increment")
    p.add_argument("--action-report-time", default="impression")
    p.add_argument("--action-attribution-windows", nargs="*", default=["7d_click", "1d_view"])
    p.add_argument("--use-unified-attribution-setting", dest="use_unified_attribution_setting", action="store_true", default=True)
    p.add_argument("--no-unified-attribution-setting", dest="use_unified_attribution_setting", action="store_false")
    p.add_argument("--summary", nargs="*")
    p.add_argument("--default-summary", action="store_true")
    p.add_argument("--async-report", action="store_true")
    p.add_argument("--no-auto-async", dest="auto_async", action="store_false", default=True)
    p.add_argument("--sort", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.set_defaults(func=commands.command_insights_get)

    activities = meta_subparsers.add_parser("activities", aliases=["activity"])
    activities_sub = activities.add_subparsers(dest="activities_command", required=True)
    p = activities_sub.add_parser("get")
    add_common_auth_arguments(p)
    p.add_argument("--since", help="Activity window start, usually YYYY-MM-DD.")
    p.add_argument("--until", help="Activity window end, usually YYYY-MM-DD.")
    p.add_argument("--fields", nargs="*")
    p.add_argument("--limit", type=int, default=100)
    p.add_argument("--max-pages", type=int, default=1)
    p.set_defaults(func=commands.command_activities_get)

    landing_pages = meta_subparsers.add_parser("landing-pages", aliases=["landing-page", "landings"])
    landing_pages_sub = landing_pages.add_subparsers(dest="landing_pages_command", required=True)
    p = landing_pages_sub.add_parser("analyze")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--date-preset", default="last_14d")
    p.add_argument("--account-limit", type=int, default=10, help="Top spend ad accounts to analyze.")
    p.add_argument("--top", type=int)
    p.add_argument("--limit", type=int, default=5000, help="Per-account ad insights page size.")
    p.add_argument(
        "--profile",
        choices=["batch", "full"],
        default="full",
        help="batch uses insight URL breakdowns and avoids per-ad story/context deep fetches; full keeps deep landing resolution.",
    )
    p.add_argument(
        "--max-ad-context-fetches",
        type=int,
        help="Maximum per-ad context lookups after insight URL breakdowns. In batch profile defaults to 0.",
    )
    p.add_argument("--async-report", action="store_true", help="Force Meta async insights report runs for ad-level reporting.")
    p.add_argument("--no-auto-async", dest="auto_async", action="store_false", default=True)
    p.add_argument(
        "--no-product",
        dest="no_product",
        action="store_true",
        default=True,
        help="Skip product page scraping/enrichment. This is the default.",
    )
    p.add_argument(
        "--product",
        dest="no_product",
        action="store_false",
        help="Enable product page scraping/enrichment.",
    )
    p.add_argument("--product-limit", type=int, default=50, help="Maximum ranked landing pages to product-enrich.")
    p.add_argument("--include-ads", action="store_true", help="Include all ads under each landing page group.")
    p.add_argument("--no-previews", action="store_true", default=False, help="Skip ad/creative preview image and URL enrichment.")
    p.set_defaults(func=commands.command_landing_pages_analyze)

    apps = meta_subparsers.add_parser("apps", aliases=["app-discovery"])
    apps_sub = apps.add_subparsers(dest="apps_command", required=True)
    p = apps_sub.add_parser("analyze")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--date-preset", default="last_14d")
    p.add_argument("--account-limit", type=int, default=2, help="Top spend ad accounts to probe.")
    p.add_argument("--campaign-limit", type=int, default=20, help="Top spend campaigns to probe per account.")
    p.add_argument(
        "--profile",
        choices=["batch", "full"],
        default="full",
        help="batch caps campaign probing for multi-account W2A/app checks.",
    )
    p.add_argument("--include-campaigns", action="store_true", help="Include campaign-level app evidence under each app group.")
    p.set_defaults(func=commands.command_apps_analyze)

    user_type = meta_subparsers.add_parser(
        "user-type",
        aliases=["customer-type", "account-type", "classify-user"],
        help="Classify the token owner's advertiser vertical from top-spend Meta campaigns.",
    )
    user_type_sub = user_type.add_subparsers(dest="user_type_command", required=True)
    p = user_type_sub.add_parser("analyze")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--date-preset", default="last_14d")
    p.add_argument("--account-limit", type=int, default=10, help="Top spend ad accounts to analyze.")
    p.add_argument("--campaign-limit", type=int, default=10, help="Top spend campaigns to analyze per account.")
    p.add_argument("--ad-limit", type=int, default=5, help="Top spend ads to inspect per campaign for landing URLs.")
    p.add_argument("--content-limit", type=int, default=60, help="Maximum landing/app-store URLs to scrape for classification.")
    p.add_argument(
        "--profile",
        choices=["batch", "full"],
        default="full",
        help="batch lowers campaign/ad/content probing and skips page-token story lookups.",
    )
    p.add_argument("--include-evidence", action="store_true", help="Include matched text snippets and scraped content details.")
    p.set_defaults(func=commands.command_user_type_analyze)

    metrics = meta_subparsers.add_parser("metrics", help="Meta metric probe helpers")
    metrics_sub = metrics.add_subparsers(dest="metrics_command", required=True)
    p = metrics_sub.add_parser("probe")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--date-preset", default="last_14d")
    p.add_argument("--account-limit", type=int, default=10, help="Top spend accounts to probe when --account is omitted.")
    p.add_argument("--limit", type=int, default=25, help="Per metric-group insight row limit.")
    p.add_argument("--group", dest="groups", action="append", help="Probe only this metric group. Repeat for multiple groups.")
    p.add_argument(
        "--profile",
        choices=["light", "batch", "vertical", "full"],
        default="batch",
        help="Probe profile. batch is optimized for multi-account runs; full is for connector QA.",
    )
    p.add_argument("--async-report", action="store_true", help="Force Meta async insights report runs for heavy groups.")
    p.add_argument("--no-auto-async", dest="auto_async", action="store_false", default=True)
    p.set_defaults(func=commands.command_metrics_probe)

    audience = meta_subparsers.add_parser("audience", aliases=["audience-breakdown"])
    audience_sub = audience.add_subparsers(dest="audience_command", required=True)
    p = audience_sub.add_parser("breakdown")
    add_common_auth_arguments(p)
    p.add_argument("--since")
    p.add_argument("--until")
    p.add_argument("--date-preset", default="last_14d")
    p.add_argument(
        "--breakdown",
        dest="breakdowns",
        action="append",
        choices=["country", "age_gender", "placement", "device"],
        help="Audience lens to fetch. Repeat to limit the run; defaults to all key lenses.",
    )
    p.add_argument("--top", type=int, default=20, help="Maximum segments kept per breakdown.")
    p.add_argument("--limit", type=int, default=500, help="Per-breakdown insight row limit.")
    p.add_argument("--async-report", action="store_true", help="Force Meta async insights report runs.")
    p.add_argument("--no-auto-async", dest="auto_async", action="store_false", default=True)
    p.set_defaults(func=commands.command_audience_breakdown)

    targeting = meta_subparsers.add_parser("targeting")
    targeting_sub = targeting.add_subparsers(dest="targeting_command", required=True)
    p = targeting_sub.add_parser("interests")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("query")
    p.add_argument("--limit", type=int, default=25)
    p.set_defaults(func=commands.command_targeting_interests)

    p = targeting_sub.add_parser("suggestions")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--interests", nargs="+", required=True)
    p.add_argument("--limit", type=int, default=25)
    p.set_defaults(func=commands.command_targeting_suggestions)

    p = targeting_sub.add_parser("locations")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("query")
    p.add_argument("--type", dest="location_types", nargs="*")
    p.add_argument("--limit", type=int, default=25)
    p.set_defaults(func=commands.command_targeting_locations)

    p = targeting_sub.add_parser("behaviors")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--limit", type=int, default=50)
    p.set_defaults(func=commands.command_targeting_behaviors)

    p = targeting_sub.add_parser("demographics")
    add_common_auth_arguments(p, needs_account=False)
    p.add_argument("--class", dest="category_class", default="demographics")
    p.add_argument("--limit", type=int, default=50)
    p.set_defaults(func=commands.command_targeting_demographics)

    p = targeting_sub.add_parser("estimate")
    add_common_auth_arguments(p)
    p.add_argument("--targeting", "--targeting-json", dest="targeting_json", required=True)
    p.set_defaults(func=commands.command_targeting_estimate)

    config = meta_subparsers.add_parser("config")
    config_sub = config.add_subparsers(dest="config_command", required=True)
    p = config_sub.add_parser("set")
    p.add_argument("--account")
    p.add_argument("--key")
    p.add_argument("--value")
    p.set_defaults(func=commands.command_config_set)

    p = config_sub.add_parser("get")
    p.add_argument("key")
    p.set_defaults(func=commands.command_config_get)

    p = config_sub.add_parser("list")
    p.set_defaults(func=commands.command_config_list)

    p = config_sub.add_parser("unset")
    p.add_argument("key")
    p.set_defaults(func=commands.command_config_unset)

    config_accounts = config_sub.add_parser("accounts")
    config_accounts_sub = config_accounts.add_subparsers(dest="config_accounts_command", required=True)
    p = config_accounts_sub.add_parser("list")
    p.set_defaults(func=commands.command_config_accounts_list)

    p = config_accounts_sub.add_parser("add")
    p.add_argument("alias")
    p.add_argument("account_id")
    p.add_argument("--label")
    p.set_defaults(func=commands.command_config_accounts_add)

    p = config_accounts_sub.add_parser("remove")
    p.add_argument("alias")
    p.set_defaults(func=commands.command_config_accounts_remove)

    validate = meta_subparsers.add_parser("validate")
    validate_sub = validate.add_subparsers(dest="validate_command", required=True)
    p = validate_sub.add_parser("creative")
    add_common_auth_arguments(p)
    p.add_argument("--name")
    p.add_argument("--page-id")
    p.add_argument("--instagram-user-id")
    p.add_argument("--instagram-actor-id", dest="instagram_actor_id")
    p.add_argument("--video-id")
    p.add_argument("--image-hash")
    p.add_argument("--link")
    p.add_argument("--message")
    p.add_argument("--headline")
    p.add_argument("--description")
    p.add_argument("--call-to-action", default="SHOP_NOW")
    p.add_argument("--object-story-id")
    p.add_argument("--object-story-spec")
    p.add_argument("--asset-feed-spec")
    p.add_argument("--media-sourcing-spec")
    p.add_argument("--url-tags")
    add_payload_arguments(p)
    p.add_argument("--cleanup", action="store_true")
    p.set_defaults(func=commands.command_validate_creative)

    p = validate_sub.add_parser("ad-link")
    add_common_auth_arguments(p)
    p.add_argument("--name")
    p.add_argument("--adset-id", required=True)
    p.add_argument("--creative-id", required=True)
    p.add_argument("--cleanup", action="store_true")
    p.set_defaults(func=commands.command_validate_ad_link)

    p = validate_sub.add_parser("promoted-object")
    add_common_auth_arguments(p)
    p.add_argument("--campaign-objective", required=True)
    p.add_argument("--optimization-goal", required=True)
    p.add_argument("--billing-event", default="IMPRESSIONS")
    p.add_argument("--targeting", "--targeting-json", dest="targeting_json", required=True)
    p.add_argument("--promoted-object", "--promoted-object-json", dest="promoted_object_json", required=True)
    p.add_argument("--cleanup", action="store_true")
    p.set_defaults(func=commands.command_validate_promoted_object)

    debug = meta_subparsers.add_parser("debug")
    debug_sub = debug.add_subparsers(dest="debug_command", required=True)
    p = debug_sub.add_parser("graph")
    add_common_auth_arguments(p)
    p.add_argument("--method", required=True)
    p.add_argument("--path", required=True)
    p.add_argument("--params-json")
    p.add_argument("--data-json")
    p.add_argument("--data-file")
    p.set_defaults(func=commands.command_debug_graph)

    migrate = meta_subparsers.add_parser("migrate")
    migrate_sub = migrate.add_subparsers(dest="migrate_command", required=True)
    p = migrate_sub.add_parser("export")
    p.add_argument("--export-dir", required=True)
    p.add_argument("--source-account-id", required=True)
    p.add_argument("--campaign-id", action="append", required=True)
    p.add_argument("--source-access-token")
    p.add_argument("--json", action="store_true", default=True)
    p.set_defaults(func=commands.command_migrate_export)

    p = migrate_sub.add_parser("plan")
    p.add_argument("--export-dir", required=True)
    p.add_argument("--source-account-id", required=True)
    p.add_argument("--target-account-id", required=True)
    p.add_argument("--target-access-token")
    p.add_argument("--json", action="store_true", default=True)
    p.set_defaults(func=commands.command_migrate_plan)

    p = migrate_sub.add_parser("run")
    p.add_argument("--export-dir", required=True)
    p.add_argument("--source-account-id", required=True)
    p.add_argument("--target-account-id", required=True)
    p.add_argument("--page-id")
    p.add_argument("--instagram-user-id")
    p.add_argument("--pixel-id", required=True)
    p.add_argument("--target-application-id")
    p.add_argument("--target-object-store-url")
    p.add_argument("--promoted-object-overrides", "--promoted-object-overrides-json", dest="promoted_object_overrides_json")
    p.add_argument("--source-access-token")
    p.add_argument("--target-access-token")
    p.add_argument("--reuse-existing-by-name", action="store_true", default=True)
    p.add_argument("--no-reuse-existing-by-name", action="store_false", dest="reuse_existing_by_name")
    p.add_argument("--job-id")
    p.add_argument("--json", action="store_true", default=True)
    p.set_defaults(func=commands.command_migrate_run)

    p = migrate_sub.add_parser("status")
    p.add_argument("--job-id", required=True)
    p.add_argument("--json", action="store_true", default=True)
    p.set_defaults(func=commands.command_migrate_status)

    p = migrate_sub.add_parser("resume")
    p.add_argument("--job-id", required=True)
    p.add_argument("--source-access-token")
    p.add_argument("--target-access-token")
    p.add_argument("--json", action="store_true", default=True)
    p.set_defaults(func=commands.command_migrate_resume)
